<?php
/**
 * Annual Checklist Interface
 *
 * about.phtml
 * Info - Special 2010 Edition
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
printf($this->translate('Info_special_edition'), $this->app->edition);
?>
</div>
<?php echo $this->navigator_top;?>
<div class="info_content">




<p class="iyb-slogan">In the 2019 Annual Checklist<br><span style="font-weight:normal">(21st April 2019)</span></p>

<p class="field_header">There are 4 new taxonomic databases:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Fossil Ginkgoales</p>
<p>&#8226; StaphBase: Staphyliniformia world catalog database</p>
<p>&#8226; ThripsWiki</p>
<p>&#8226; WoRMS World Amphipoda Database</p>
</div>
<p>&nbsp;</p>

<p class="field_header">95 databases have been updated:</p>
<div style='margin-left: 10px;'>

<p>&#8226; 3i Curculionidae</p>
<p>&#8226; ELPT</p>
<p>&#8226; ILDIS <i>(updated distribution)</i></p>
<p>&#8226; LDL Neurotperida</p>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; PaleoBioDB <i>(selected paleo taxa from Pinopsida, Liliopsida & Magnoliopsida)</i></p>
<p>&#8226; Scarabs <i>(3 updates in a year cycle)</i></p>
<p>&#8226; SF Aphid </p>
<p>&#8226; SF Chrysididae</p>
<p>&#8226; SF Cockroach</p>
<p>&#8226; SF Coleorrhyncha</p>
<p>&#8226; SF Coreoidea</p>
<p>&#8226; SF Dermaptera</p>
<p>&#8226; SF Embioptera</p>
<p>&#8226; SF Grylloblattodea</p>
<p>&#8226; SF Lygaeoidea</p>
<p>&#8226; SF Mantodea</p>
<p>&#8226; SF Mantophasmatodea</p>
<p>&#8226; SF Orthoptera</p>
<p>&#8226; SF Phasmida</p>
<p>&#8226; SF Plecoptera</p>
<p>&#8226; SF Psocodea</p>
<p>&#8226; SF Zoraptera</p>
<p>&#8226; The World List of Cycads</p>
<p>&#8226; World Ferns</p>
<p>&#8226; World Plants</p>
<p>&#8226; World Spider Catalog <i>(2 updates in a year cycle)</i></p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 60 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other changes and improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; <b>There will be no Catalogue of Life on DVD anymore.</b></p> 
<p>&#8226; Bug fixes in scientific names reported by Ari Örn, Helsinki, Finland.</p>
<p>&#8226; Fixes in genera attached to different parts of the classification after notifications from Jonathan Coddington, Smithsonian National Museum of Natural History, Washington DC, USA.</p>
<p>&#8226; Position of paleo turtle families in the classification has been corrected following helpful comments from Scott Thomson, Museu de Zoologia da Universidade de São Paulo, Brasil & Chelonian Research Institute, FL, USA.</p>
<p>&#8226; New species of orangutan Pongo tapanuliensis (ITIS) was included after kind reminder from Philippe Barbry, France.</p>
</div>
<p>&nbsp;</p>


<br/>
<hr/>
<p>&nbsp;</p>








<p class="iyb-slogan">In the Catalogue of Life, 25th March 2019</p>

<p class="field_header">80 databases have been updated:</p>
<div style='margin-left: 10px;'>

<p>&#8226; Scarabs <i>(third update in a year cycle)</i></p>
<p>&#8226; 3i Curculionidae</p>
<p>&#8226; The World List of Cycads</p>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; SF Mantophasmatodea</p>
<p>&#8226; SF Orthoptera</p>
<p>&#8226; SF Phasmida</p>
<p>&#8226; SF Plecoptera</p>
<p>&#8226; SF Psocodea</p>
<p>&#8226; SF Zoraptera</p>
<p>&#8226; ILDIS <i>(updated distribution)</i></p>
<p>&#8226; PaleoBioDB <i>(selected paleo taxa from Pinopsida, Liliopsida & Magnoliopsida)</i></p> 
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 60 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Additional cleaning of duplicated names across all taxa.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>





<p class="iyb-slogan">In the Catalogue of Life, 26th February 2019</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Brought back 218 previously missing species and related infraspecific taxa in World Ferns.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 20th February 2019</p>

<p class="field_header">72 databases have been updated:</p>
<div style='margin-left: 10px;'>

<p>&#8226; World Plants</p>
<p>&#8226; ELPT</p>
<p>&#8226; Fossil Ginkgoales</p>
<p>&#8226; World Spider Catalog <i>(second update in a year cycle)</i></p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 60 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Further fixes of bugs in scientific names.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 29th January 2019</p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; StaphBase: Staphyliniformia world catalog database by Al Newton</p>
</div>
<p>&nbsp;</p>

<p class="field_header">68 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 60 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; New species of orangutan <i>Pongo tapanuliensis</i> (ITIS) was included after kind reminder from Philippe Barbry, France.</p>
</div>
<p>&nbsp;</p>


<br/>
<hr/>
<p>&nbsp;</p>





<p class="iyb-slogan">In the Catalogue of Life, 24th December 2018</p>

<p class="field_header">69 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Ferns</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 60 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Clearing duplicated names and further fixes of bugs in scientific names reported by Ari &Ouml;rn, Helsinki, Finland.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 29th November 2018</p>

<p class="field_header">62 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ThripsWiki <i>(second update in a year cycle)</i></p> 
<p>&#8226; Scarabs <i>(second update in a year cycle)</i></p>
<p>&#8226; 60 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Further fixes of bugs in scientific names reported by Ari &Ouml;rn, Helsinki, Finland.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 30th October 2018</p>

<p class="field_header">There is a new taxonomic checklist:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ThripsWiki</p>
</div>
<p>&nbsp;</p>


<p class="field_header">68 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 60 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Fixes of bugs in scientific names reported by Ari &Ouml;rn, Helsinki, Finland.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>





<p class="iyb-slogan">In the Catalogue of Life, 24th September 2018</p>

<p class="field_header">70 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; LDL Neurotperida</p>
<p>&#8226; World Spider Catalog</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 60 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Position of paleo turtle families in the classification has been corrected following helpful comments from Scott Thomson, Museu de Zoologia da Universidade de S&atilde;o Paulo, Brasil & Chelonian Research Institute, FL, USA.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 31st July 2018</p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WoRMS World Amphipoda Database</p>
</div>
<p>&nbsp;</p>

<p class="field_header">67 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 59 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>





<p class="iyb-slogan">In the Catalogue of Life, 30th June 2018</p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Fossil Ginkgoales</p>
</div>
<p>&nbsp;</p>

<p class="field_header">78 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Scarabs</p>
<p>&#8226; SF Aphid, SF Chrysididae, SF Cockroach, SF Coleorrhyncha, SF Coreoidea, SF Dermaptera, SF Embioptera, SF Grylloblattodea, SF Lygaeoidea, SF Mantodea have been updated through semi-automated process using CoL Workbench templates.</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 59 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 31st May 2018</p>

<p class="field_header">67 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 59 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the 2018 Annual Checklist<br><span style="font-weight:normal">(30th April 2018)</span></p>

<p class="field_header">There are 27 new databases plus new global sectors from ITIS: </p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i World Auchenorrhyncha Database now aggregates all data from 3i Cicadoidea, 3i Cicadellinae, 3i Typhlocybinae and includes checklists for Aetalionidae, Melizoderidae & Myerslopiidae.</p>
<p>&#8226; Gymnodinium: The dinoflagellate genus Gymnodinium checklist</p>
<p>&#8226; IRMNG: Interim Register of Marine and Nonmarine Genera (classification down to genus rank in Chromista, Protozoa and in algae phyla Charophyta, Chlorophyta, Glaucophyta, Rhodophyta).</p>
<p>&#8226; ITIS Global: family Chaetocerotaceae & genus Navicula (Chromista - Ochrophyta - Bacillariophyceae); superfamilies Leptopodoidea, Saldoidea and families Aphelocheiridae, Hermatobatidae, Hydrometridae, Macroveliidae, Mesoveliidae, Paraphrynoveliidae, Potamocoridae, Veliidae (Insecta - Hemiptera)</p>
<p>&#8226; Jewel Beetles</p>
<p>&#8226; Pterophoroidea: Catalogue of the Pterophoroidea of the World</p>
<p>&#8226; SF Coleorrhyncha: Coleorrhyncha Species File</p>
<p>&#8226; SF Isoptera: Isoptera Species File</p>
<p>&#8226; WoRMS Antipatharia. It has replaced URMO data.</p>
<p>&#8226; WoRMS Appendicularia</p>
<p>&#8226; WoRMS Ascidiacea</p>
<p>&#8226; WoRMS Ceriantharia</p>
<p>&#8226; WoRMS Copepoda</p>
<p>&#8226; WoRMS Corallimorpharia. It has replaced URMO data.</p>
<p>&#8226; WoRMS Ctenophora</p>
<p>&#8226; WoRMS Cubozoa</p>
<p>&#8226; WoRMS Hexacoral. It is a new version for Hexacorallians of the World.</p>
<p>&#8226; WoRMS Loricifera</p>
<p>&#8226; WoRMS MilliBase. It has replaced its predecessor SysMyr.</p>
<p>&#8226; WoRMS Ostracoda</p>
<p>&#8226; WoRMS PycnoBase</p>
<p>&#8226; WoRMS Scleractinia. It has replaced URMO data.</p>
<p>&#8226; WoRMS Scyphozoa</p>
<p>&#8226; WoRMS Staurozoa</p>
<p>&#8226; WoRMS Thaliacea</p>
<p>&#8226; WoRMS Turbellarians. It has replaced FADA Turbellaria, FaEu Turbellaria, WoRMS Proseriata-Kalyptorhynchia, WoRMS Acoelomorpha and turbellarians from ITIS Regional & NZIB.</p>
<p>&#8226; WoRMS Zoantharia It has replaced URMO data.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">89 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Curculio <i>(4 updates in a year cycle)</i></p>
<p>&#8226; CarabCat</p>
<p>&#8226; Dothideomycetes</p>
<p>&#8226; ELPT</p>
<p>&#8226; FishBase <i> (2 updates in a year cycle) </i></p>
<p>&#8226; Glomeromycota</p>
<p>&#8226; HymIS (families Pompilidae and Rhopalosomatidae)</p>
<p>&#8226; ITIS Global: classes Aves & Mammalia; order Opiliones (Arachnida); families Agyrtidae & Silphidae (Coleoptera), Histeridae (Insecta - Coleoptera - Histeroidea) & Hydraenidae (Insecta - Coleoptera - Staphylinoidea)</p>
<p>&#8226; ITIS Regional: superfamilies Cleroidea, Cucujoidea, Tenebrionoidea, Chrysomeloidea (except family Cerambycidae), Lymexyloidea & Coccinelloidea from infraorder Cucujiformia (Coleoptera); families Gyrinidae & Scirtidae (Coleoptera)</p>
<p>&#8226; LDL Neuropterida</p>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; PaleoBioDB</p>
<p>&#8226; Phyllachorales</p>
<p>&#8226; Rhytismatales</p>
<p>&#8226; RJB Geranium</p>
<p>&#8226; Saccharomycetes</p>
<p>&#8226; Scarabs <i>(2 updates in a year cycle)</i></p>
<p>&#8226; Species Fungorum</p>
<p>&#8226; Trichomycetes</p>
<p>&#8226; WCSP. This database has replaced LecyPages and ITIS Eucommiaceae and Petenaeaceae.</p>
<p>&#8226; World Ferns <i>(4 updates in a year cycle through semi-automated process)</i></p>
<p>&#8226; World Plants <i>(4 updates in a year cycle through semi-automated process)</i>; it includes replacement for IOPI Global Plant Checklist, ChenoBase, Solanaceae Source, LHD family Lacistemataceae and WCSP family Paracryphiaceae.</p>
<p>&#8226; World Spider Catalog <i>(2 updates in a year cycle)</i></p>
<p>&#8226; World Wide Wattle</p>
<p>&#8226; Xylariaceae</p>
<p>&#8226; Zygomycetes</p>
&nbsp; &nbsp; &nbsp;15 Species File checklists <i>(2 updates in a year cycle through semi-automated process)</i>:
<p>&#8226; Aphid Species File</p>
<p>&#8226; Chrysididae Species File</p>
<p>&#8226; Cockroach Species File</p>
<p>&#8226; Coreoidea Species File</p>
<p>&#8226; Dermaptera Species File</p>
<p>&#8226; Embioptera Species File</p>
<p>&#8226; Grylloblattodea Species File</p>
<p>&#8226; Lygaeoidea Species File</p>
<p>&#8226; Mantodea Species File</p>
<p>&#8226; Mantophasmatodea Species File</p>
<p>&#8226; Orthoptera Species File</p>
<p>&#8226; Phasmida Species File</p>
<p>&#8226; Plecoptera Species File</p>
<p>&#8226; Psocodea Species File</p>
<p>&#8226; Zoraptera Species File</p>
&nbsp; &nbsp; &nbsp;8 checklists powered by DBTNT software <i>(12 updates in a year cycle through automated process)</i>:
<p>&#8226; Brentidae</p>
<p>&#8226; COOL</p>
<p>&#8226; FLOW</p>
<p>&#8226; Lace Bugs Database</p>
<p>&#8226; PsilList</p>
<p>&#8226; Strepsiptera</p>
<p>&#8226; Tessaratomidae</p>
<p>&#8226; The White-Files</p>
&nbsp; &nbsp; &nbsp;40 WoRMS checklists <i>(12 updates in a year cycle through automated process)</i>:
<p>&#8226; WoRMS Asteroidea: World Asteroidea database</p>
<p>&#8226; WoRMS Bochusacea: World List of Bochusacea</p>
<p>&#8226; WoRMS Brachypoda: World List of Brachypoda</p>
<p>&#8226; WoRMS Brachyura: World List of marine Brachyura</p>
<p>&#8226; WoRMS Bryozoa: World List of Bryozoa</p>
<p>&#8226; WoRMS Cephalochordata: World list of Cephalochordata</p>
<p>&#8226; WoRMS Cestoda: World list of Cestoda</p>
<p>&#8226; WoRMS Chaetognatha: World list of Chaetognatha</p>
<p>&#8226; WoRMS Cumacea: World Cumacea database</p>
<p>&#8226; WoRMS Echinoidea: World Echinoidea Database</p>
<p>&#8226; WoRMS Foraminifera: World Foraminifera Database</p>
<p>&#8226; WoRMS Gastrotricha: World Gastrotricha Database</p>
<p>&#8226; WoRMS Gnathostomulida: World list of Gnathostomulida</p>
<p>&#8226; WoRMS Holothuroidea: World List of Holothuroidea</p>
<p>&#8226; WoRMS Hydrozoa: World Hydrozoa database</p>
<p>&#8226; WoRMS Isopoda: World Marine, Freshwater and Terrestrial Isopod Crustaceans database</p>
<p>&#8226; WoRMS Kinorhyncha: World list of Kinorhyncha</p>
<p>&#8226; WoRMS Leptostraca: World List of Leptostraca</p>
<p>&#8226; WoRMS Merostomata: World list of Merostomata</p>
<p>&#8226; WoRMS Mollusca: MolluscaBase</p>
<p>&#8226; WoRMS Monogenea: World list of Monogenea</p>
<p>&#8226; WoRMS Mystacocarida: World List of Mystacocarida</p>
<p>&#8226; WoRMS Myxozoa: World list of Myxozoa</p>
<p>&#8226; WoRMS Nemertea: World Nemertea database</p>
<p>&#8226; WoRMS Octocorallia: World list of Octocorallia</p>
<p>&#8226; WoRMS Oligochaeta: World List of Marine Oligochaeta</p>
<p>&#8226; WoRMS Ophiuroidea: World Ophiuroidea database</p>
<p>&#8226; WoRMS Orthonectida: World list of Orthonectida</p>
<p>&#8226; WoRMS Placozoa: World Placozoa Database</p>
<p>&#8226; WoRMS Polychaeta: World Polychaeta database</p>
<p>&#8226; WoRMS Polycystina: World list of Polycystina (Radiolaria)</p>
<p>&#8226; WoRMS Porifera: World Porifera database</p>
<p>&#8226; WoRMS Priapulida: World list of Priapulida</p>
<p>&#8226; WoRMS Remipedia: World Remipedia Database</p>
<p>&#8226; WoRMS Rhombozoa: World list of Rhombozoa</p>
<p>&#8226; WoRMS Tanaidacea: World List of Tanaidacea</p>
<p>&#8226; WoRMS Tantulocarida: World List of Tantulocarida</p>
<p>&#8226; WoRMS Thermosbaenacea: World List of Thermosbaenacea</p>
<p>&#8226; WoRMS Trematoda: World list of Trematoda</p>
<p>&#8226; WoRMS Xenoturbellida: World List of Xenoturbellida</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Positions of plant families Casuarinaceae, Quillajaceae, Sarcolaenaceae and genus Rhoiptelea in the classification have been corrected following helpful comments from Vojt&#283;ch Zavadil, Krkonose Mountains National Park (KRNAP), Czech Republic.</p>
<p>&#8226; We have corrected position of plant family Juncaceae and have added some missing species from various families after kind comments from Alexey Seregin, MW Herbarium, Moscow State University, Russia.</p>
<p>&#8226; Fixes of bugs, which have been kindly reported by Ari &Ouml;rn, Helsinki, Finland.</p>
<p>&#8226; Links to BHL website have been corrected in CarabCat bibliographic references.</p>
<p>&#8226; Additional cleanings were applied in World Plants and MOST checklists.</p>
<p>&#8226; Final cleanings and bug fixes through whole database.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 30th April 2018</p>

<p class="field_header">There is a new global checklist and classification from IRMNG:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WoRMS MilliBase. This database has replaced its predecessor SysMyr.</p>
<p>&#8226; IRMNG: Interim Register of Marine and Nonmarine Genera (classification down to genus rank in Chromista, Protozoa and in algae phyla Charophyta, Chlorophyta, Glaucophyta, Rhodophyta).</p>
</div>
<p>&nbsp;</p>

<p class="field_header">70 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; PaleoBioDB</p>
<p>&#8226; World Ferns <i>(fourth update in a year cycle)</i></p>
<p>&#8226; World Plants <i>(fourth update in a year cycle)</i></p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 59 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Final cleanings and bug fixes through whole database.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 27th March 2018</p>

<p class="field_header">There is a new global checklist:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Pterophoroidea: Catalogue of the Pterophoroidea of the World</p>
</div>
<p>&nbsp;</p>

<p class="field_header">70 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Curculio <i>(fourth update in a year cycle)</i></p>
<p>&#8226; FishBase <i>(second update in a year cycle)</i></p>
<p>&#8226; Scarabs <i>(second update in a year cycle)</i></p>
<p>&#8226; World Wide Wattle</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 59 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Additional cleanings through database and fixes of bugs, which have been kindly reported by Ari &Ouml;rn, Helsinki, Finland.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 26th February 2018</p>

<p class="field_header">There is a new global checklist:</p>
<div style='margin-left: 10px;'>
<p>&#8226; SF Isoptera: Isoptera Species File</p>
</div>
<p>&nbsp;</p>

<p class="field_header">73 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ELPT</p>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; Dothideomycetes</p>
<p>&#8226; Saccharomycetes</p>
<p>&#8226; Species Fungorum</p>
<p>&#8226; World Spider Catalog <i>(second update in a year cycle)</i></p>
</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 59 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Missing species of Myerslopiidae family have been brought back in 3i Auchenorrhyncha.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 30th January 2018</p>

<p class="field_header">74 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Curculio <i>(third update in a year cycle)</i></p>
<p>&#8226; Glomeromycota</p>
<p>&#8226; Phyllachorales</p>
<p>&#8226; Rhytismatales</p>
<p>&#8226; Trichomycetes</p>
<p>&#8226; Xylariaceae</p>
<p>&#8226; Zygomycetes</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, Psil'List, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 59 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Positions of plant families Casuarinaceae, Quillajaceae, Sarcolaenaceae and genus Rhoiptelea in the classification have been corrected following helpful comments from Vojt&#283;ch Zavadil, Krkonose Mountains National Park (KRNAP), Czech Republic.</p>
<p>&#8226; We have corrected position of plant family Juncaceae and have added some missing species from various families after kind comments from Alexey Seregin, MW Herbarium, Moscow State University, Russia.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 20th December 2017</p>

<p class="field_header">There are 7 new global checklists:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i World Auchenorrhyncha Database now aggregates all data from 3i Cicadoidea, 3i Cicadellinae, 3i Typhlocybinae and includes checklists for Aetalionidae, Melizoderidae & Myerslopiidae.</p>
<p>&#8226; SF Coleorrhyncha</p>
<p>&#8226; WoRMS Turbellarians. This checklist has replaced FADA Turbellaria, FaEu Turbellaria, WoRMS Proseriata-Kalyptorhynchia, WoRMS Acoelomorpha and turbellarians from ITIS Regional & NZIB.</p>
<p>&#8226; WoRMS Antipatharia. It has replaced URMO data.</p>
<p>&#8226; WoRMS Corallimorpharia. It has replaced URMO data.</p>
<p>&#8226; WoRMS Scleractinia. It has replaced URMO data.</p>
<p>&#8226; WoRMS Zoantharia. It has replaced URMO data.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">77 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; All 15 Species Files have been updated through semi-automated process using CoL Workbench templates <i>(second update in a year cycle)</i>.</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 54 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Links to BHL website have been corrected in CarabCat bibliographic references.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>






<p class="iyb-slogan">In the Catalogue of Life, 28th November 2017</p>

<p class="field_header">66 databases have been updated:</p>
<div style='margin-left: 10px;'>

<p>&#8226; CarabCat</p>
<p>&#8226; WCSP. This database has replaced LecyPages and ITIS Eucommiaceae and Petenaeaceae.</p>
<p>&#8226; World Plants <i>(third update in a year cycle)</i>. This database has replaced LHD checklist.</p>
<p>&#8226; World Ferns <i>(third update in a year cycle)</i></p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 54 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>


<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 30th October 2017</p>

<p class="field_header">65 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Curculio <i>(second update in a year cycle)</i></p>
<p>&#8226; RJB Geranium</p>
<p>&#8226; Brought back URMO data for orders Antipatharia, Ceriantharia, Corallimorpharia, Scleractinia, Zoantharia (Cnidaria) from 2017 Annual Checklist</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 54 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Bibliographic references were added to Jewel Beetles checklist</p>
<p>&#8226; Additional cleanings were applied to World Plants and MOST</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 29th September 2017</p>

<p class="field_header">There are two new global checklists:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Jewel Beetles</p>
<p>&#8226; WoRMS Copepoda</p>
</div>
<p>&nbsp;</p>

<p class="field_header">65 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; HymIS (families Pompilidae and Rhopalosomatidae)</p>
<p>&#8226; World Plants <i>(second update in a year cycle)</i>. New update includes replacements for IOPI Global Plant Checklist, ChenoBase, Solanaceae Source, LHD family Lacistemataceae and WCSP family Paracryphiaceae.</p>
<p>&#8226; World Spider Catalog</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 54 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>





<p class="iyb-slogan">In the Catalogue of Life, 25th August 2017</p>

<p class="field_header">There is a new global checklist:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Aetalionidae, Melizoderidae, Myerslopiidae</p>
</div>
<p>&nbsp;</p>

<p class="field_header">66 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; FishBase</p>
<p>&#8226; World Ferns <i>(second update in a year cycle)</i></p>
<p>&#8226; ITIS Global: families Agyrtidae & Silphidae (Coleoptera) and order Opiliones (Arachnida).</p>
<p>&#8226; ITIS Regional: six superfamilies (Cleroidea, Cucujoidea, Tenebrionoidea, Chrysomeloidea (except family Cerambycidae), Lymexyloidea & Coccinelloidea) from infraorder Cucujiformia (Coleoptera); families Gyrinidae & Scirtidae (Coleoptera).</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; WoRMS Cestoda. It has replaced CoL proto-GSD previously built with ITIS Regional, NZIB and marine tapeworms from WoRMS.</p>
<p>&#8226; WoRMS Monogenea. It has replaced CoL proto-GSD previously built with ITIS Regional, NZIB and marine monogenean flatworms from WoRMS.</p>
<p>&#8226; WoRMS Trematoda. It has replaced CoL proto-GSD previously built with ITIS Regional, NZIB and marine trematods from WoRMS.</p>
<p>&#8226; 51 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 26th July 2017</p>

<p class="field_header">There are 11 new global checklists from WoRMS as replacements for URMO:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WoRMS Appendicularia</p>
<p>&#8226; WoRMS Ascidiacea</p>
<p>&#8226; WoRMS Ceriantharia</p>
<p>&#8226; WoRMS Ctenophora</p>
<p>&#8226; WoRMS Cubozoa</p>
<p>&#8226; WoRMS Echiura</p>
<p>&#8226; WoRMS Loricifera</p>
<p>&#8226; WoRMS PycnoBase</p>
<p>&#8226; WoRMS Scyphozoa</p>
<p>&#8226; WoRMS Staurozoa</p>
<p>&#8226; WoRMS Thaliacea</p>

</div>
<p>&nbsp;</p>

<p class="field_header">64 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Scarabs</p>
<p>&#8226; 15 Species Files (AphidSF, ChrysididaeSF, CockroachSF, CoreoideaSF, DermapteraSF, EmbiopteraSF, GrylloblattodeaSF, LygaeoideaSF, MantodeaSF, MantophasmatodeaSF, OrthopteraSF, PhasmidaSF, PlecopteraSF, PsocodeaSF, ZorapteraSF) have been updated through automated process using CoL Workbench templates and manual editorial adjustments.</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 40 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>






<p class="iyb-slogan">In the Catalogue of Life, 30th June 2017</p>

<p class="field_header">There are new global checklists from ITIS and new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Gymnodinium: The dinoflagellate genus Gymnodinium checklist</p>
<p>&#8226; ITIS Global: family Chaetocerotaceae & genus Navicula (Chromista - Ochrophyta - Bacillariophyceae); superfamilies Leptopodoidea, Saldoidea and families Aphelocheiridae, Hermatobatidae, Hydrometridae, Macroveliidae, Mesoveliidae, Paraphrynoveliidae, Potamocoridae, Veliidae (Insecta - Hemiptera)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">51 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ITIS Global: families Histeridae (Insecta - Coleoptera - Histeroidea) & Hydraenidae (Insecta - Coleoptera - Staphylinoidea); classes Aves & Mammalia</p>
<p>&#8226; LDL Neuropterida</p>
<p>&#8226; 3i Curculio</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 40 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 29th May 2017</p>

<p class="field_header">There is one new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WoRMS Hexacoral. It is a new version for Hexacorallians of the World.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">48 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Ferns</p>
<p>&#8226; World Plants</p>
<p>&#8226; Brentidae, COOL, FLOW, Lace Bugs Database, PsilList, Strepsiptera, The White-Files & Tessaratomidae Database have been updated through automated process using CoL Workbench templates.</p>
<p>&#8226; 39 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 30th April 2017</p>

<p class="field_header">There is one new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WoRMS Ostracoda</p>
</div>
<p>&nbsp;</p>

<p class="field_header">46 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Brentidae</p>
<p>&#8226; COOL</p>
<p>&#8226; FLOW</p>
<p>&#8226; Lace Bugs Database</p>
<p>&#8226; Psil'list</p>
<p>&#8226; Strepsiptera</p>
<p>&#8226; The White-Files</p>
<p>&#8226; Tessaratomidae Database</p>
<p>&#8226; 38 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the 2017 Annual Checklist<br><span style="font-weight:normal">(1st April 2017)</span></p>

<p class="field_header">There are 3 new databases plus new global sectors from ITIS and World Plants: </p>
<div style='margin-left: 10px;'>

<p>&#8226; ITIS Global, phylum Hemichordata. ITIS data have replaced URMO Hemichordata.</p>
<p>&#8226; LygaeoideaSF: Lygaeoidea Species File</p>
<p>&#8226; Nepticuloidea: Nepticulidae and Opostegidae of the World. This checklist is published in the CoL at the same day as monograph paper by Erik van Nieukerken (ed) in ZooKeys <a href="https://doi.org/10.3897/zookeys.628.9799" target="_blank">doi: 10.3897/zookeys.628.9799</a> </p>
<p>&#8226; PaleoBioDB (paleoradiolarians, trilobites, paleodecapods, ammonites, belemnites, paleobrachyopods, dinosaurs and other paleoreptiles) </p>
<p>&#8226; World Plants, family Asteraceae. This new world checklist has replaced GCC. </p>

</div>
<p>&nbsp;</p>

<p class="field_header">66 databases have been updated in a year cycle: </p>
<div style='margin-left: 10px;'>

<p>&#8226; 3i Cicadellinae</p>
<p>&#8226; 3i Cicadoidea</p>
<p>&#8226; 3i Curculio</p>
<p>&#8226; 3i Typhlocybinae </p>
<p>&#8226; AphidSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; ChrysididaeSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; CockroachSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; CoreoideaSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; DermapteraSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; ELPT provides now complete world checklist of hornworts and liverworts.</p>
<p>&#8226; EmbiopteraSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; FishBase <i>(three updates in a year cycle) </i></p>
<p>&#8226; GrylloblattodeaSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; ITIS Global: classes Aves and Mammalia; order Branchiobdellida (Annelida - Clitellata); family Histeridae (Insecta - Coleoptera)</p>
<p>&#8226; ITIS Regional: superfamilies Cleroidea, Chrysomeloidea, Cucujoidea, Lymexyloidea, Tenebrionoidea and Coccinelloidea (Insecta - Coleoptera)</p>
<p>&#8226; MantodeaSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; MantophasmatodeaSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; OrthopteraSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; PhasmidaSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; PlecopteraSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; PsocodeaSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; Scarabs <i>(two updates in a year cycle)</i></p>
<p>&#8226; The Reptile Database</p>
<p>&#8226; World Ferns <i>(seven updates in a year cycle)</i></p>
<p>&#8226; World Plants <i>(five updates in a year cycle)</i></p>
<p>&#8226; World Spider Catalog <i>(two updates in a year cycle)</i></p>
<p>&#8226; WoRMS Mollusca provides now all mollusk taxa in the CoL. It has replaced AFD Pulmonata, FADA Bivalvia, MolluscaFW & NZIB. Automated monthly updates are established for WoRMS Mollusca since November 2016. </p>
<p>&#8226; WTaxa</p>
<p>&#8226; ZorapteraSF <i>(two updates in a year cycle)</i> </p>

<i>Plus</i> 36 WoRMS checklists <i>(twelve updates in a year cycle)</i>:

<p>&#8226; WoRMS Acoelomorpha: World list of Acoelomorpha</p>
<p>&#8226; WoRMS Asteroidea: World Asteroidea database</p>
<p>&#8226; WoRMS Bochusacea: World List of Bochusacea</p>
<p>&#8226; WoRMS Brachypoda: World List of Brachypoda</p>
<p>&#8226; WoRMS Brachyura: World List of marine Brachyura</p>
<p>&#8226; WoRMS Bryozoa: World List of Bryozoa</p>
<p>&#8226; WoRMS Cephalochordata: World list of Cephalochordata</p>
<p>&#8226; WoRMS Chaetognatha: World list of Chaetognatha</p>
<p>&#8226; WoRMS Cumacea: World Cumacea database</p>
<p>&#8226; WoRMS Echinoidea: World Echinoidea Database</p>
<p>&#8226; WoRMS Foraminifera: World Foraminifera Database</p>
<p>&#8226; WoRMS Gastrotricha: World Gastrotricha Database</p>
<p>&#8226; WoRMS Gnathostomulida: World list of Gnathostomulida</p>
<p>&#8226; WoRMS Holothuroidea: World List of Holothuroidea</p>
<p>&#8226; WoRMS Hydrozoa: World Hydrozoa database</p>
<p>&#8226; WoRMS Isopoda: World Marine, Freshwater and Terrestrial Isopod Crustaceans database</p>
<p>&#8226; WoRMS Kinorhyncha: World list of Kinorhyncha</p>
<p>&#8226; WoRMS Leptostraca: World List of Leptostraca</p>
<p>&#8226; WoRMS Merostomata: World list of Merostomata</p>
<p>&#8226; WoRMS Mystacocarida: World List of Mystacocarida</p>
<p>&#8226; WoRMS Nemertea: World Nemertea database</p>
<p>&#8226; WoRMS Octocorallia: World list of Octocorallia</p>
<p>&#8226; WoRMS Oligochaeta: World List of Marine Oligochaeta</p>
<p>&#8226; WoRMS Ophiuroidea: World Ophiuroidea database</p>
<p>&#8226; WoRMS Orthonectida: World list of Orthonectida</p>
<p>&#8226; WoRMS Placozoa: World Placozoa Database</p>
<p>&#8226; WoRMS Polychaeta: World Polychaeta database</p>
<p>&#8226; WoRMS Polycystina: World list of Polycystina (Radiolaria)</p>
<p>&#8226; WoRMS Porifera: World Porifera database</p>
<p>&#8226; WoRMS Priapulida: World list of Priapulida</p>
<p>&#8226; WoRMS Remipedia: World Remipedia Database</p>
<p>&#8226; WoRMS Rhombozoa: World list of Rhombozoa</p>
<p>&#8226; WoRMS Tanaidacea: World List of Tanaidacea</p>
<p>&#8226; WoRMS Tantulocarida: World List of Tantulocarida</p>
<p>&#8226; WoRMS Thermosbaenacea: World List of Thermosbaenacea</p>
<p>&#8226; WoRMS Xenoturbellida: World List of Xenoturbellida</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements: </p>
<div style='margin-left: 10px;'>

<p>&#8226; Presentation of authorstings with binomials created by Species 2000 in World Plants and World Ferns sectors has been improved. </p>
<p>&#8226; Luisa Abucay has completed semi-automation of data updating process for all Species Files and FishBase. </p>
<p>&#8226; Programmatic presentation of extinct taxa has been improved by Ruud Altenburg.</p>
<p>&#8226; French, Spanish, Chinese, Russian, Polish & Lithuanian interface languages have been improved by N. Bailly, C. Aedo, L. Ji, Y. Roskov, M. Sitko & V. Didžiulis.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 22nd March 2017</p>

<p class="field_header">38 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 38 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Programmatic presentation of extinct taxa has been improved by Ruud Altenburg.</p>
<p>&#8226; French, Spanish, Chinese, Russian, Polish & Lithuanian interface languages have been improved by N. Bailly, C. Aedo, L. Ji, Y. Roskov, M. Sitko & V. Didžiulis.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 27th February 2017</p>

<p class="field_header">There is one new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; PaleoBioDB (paleoradiolarians, trilobites, paleodecapods, ammonites, belemnites, paleobrachyopods, dinosaurs and other paleoreptiles)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">44 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ELPT (now with complete world checklist of hornworts and liverworts)</p>
<p>&#8226; FishBase <i>(third update in a year cycle)</i></p>
<p>&#8226; Scarabs <i>(second update in a year cycle)</i></p>
<p>&#8226; World Ferns  <i>(seventh update in a year cycle)</i></p>
<p>&#8226; World Plants (now including Asteraceae as a replacement for GCC; <i>fifth update in a year cycle</i>)</p>
<p>&#8226; World Spider Catalog <i>(second update in a year cycle)</i></p>
<p>&#8226; 38 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Presentation of authorstings with binomials created by Species 2000 in World Plants and Ferns sectors has been improved.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 30th January 2017</p>

<p class="field_header">44 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Cicadellinae</p>
<p>&#8226; 3i Cicadoidea</p>
<p>&#8226; 3i Curculio</p>
<p>&#8226; 3i Typhlocybinae</p>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; World Ferns <i>(sixth update in a year cycle)</i></p>
<p>&#8226; 38 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 23rd December 2016</p>

<p class="field_header">There is one new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; LygaeoideaSF: Lygaeoidea Species File</p>
</div>
<p>&nbsp;</p>

<p class="field_header">52 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; AphidSF <i>(second update in a year cycle)</i></p>
<p>&#8226; ChrysididaeSF <i>(second update in a year cycle)</i></p>
<p>&#8226; CockroachSF <i>(second update in a year cycle)</i></p>
<p>&#8226; CoreoideaSF <i>(second update in a year cycle)</i></p>
<p>&#8226; DermapteraSF <i>(second update in a year cycle)</i></p>
<p>&#8226; EmbiopteraSF <i>(second update in a year cycle)</i></p>
<p>&#8226; GrylloblattodeaSF <i>(second update in a year cycle)</i></p>
<p>&#8226; MantodeaSF <i>(second update in a year cycle)</i></p>
<p>&#8226; MantophasmatodeaSF <i>(second update in a year cycle)</i></p>
<p>&#8226; OrthopteraSF <i>(second update in a year cycle)</i></p>
<p>&#8226; PhasmidaSF <i>(second update in a year cycle)</i></p>
<p>&#8226; PlecopteraSF <i>(second update in a year cycle)</i></p>
<p>&#8226; PsocodeaSF <i>(second update in a year cycle)</i></p>
<p>&#8226; ZorapteraSF <i>(second update in a year cycle)</i></p>
<p>&#8226; 38 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Luisa Abucay has completed semi-automation of data updating process for all Species Files.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 30th November 2016</p>

<p class="field_header">42 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WTaxa</p>
<p>&#8226; FishBase <i>(second update in a year cycle through semi-automated process)</i></p>
<p>&#8226; World Ferns <i>(fifth update in a year cycle)</i></p>
<p>&#8226; World Plants <i>(fourth update in a year cycle)</i></p>
<p>&#8226; WoRMS Mollusca is covering now all mollusk taxa in the CoL and has replaced AFD Pulmonata, FADA Bivalvia, MolluscaFW & NZIB. Automated monthly updates are established for WoRMS Mollusca.</p>
<p>&#8226; 38 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Minor corrections in Tineidae NHM and LIAS datasets.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 31st October 2016</p>

<p class="field_header">There is one new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Nepticuloidea: Nepticulidae and Opostegidae of the World by Erik van Nieukerken (ed). This checklist is published in the CoL at the same day as monograph paper in ZooKeys <a href="https://doi.org/10.3897/zookeys.628.9799" target="_blank">doi: 10.3897/zookeys.628.9799</a>.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">39 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Ferns<i> (fourth update in a year cycle)</i></p>
<p>&#8226; World Plants<i> (third update in a year cycle)</i></p>
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 28th September 2016</p>

<p class="field_header">40 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Ferns <i>(third update in a year cycle)</i></p>
<p>&#8226; FishBase<i>(through automated process)</i></p>
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Luisa Abucay has completed semi-automation of data updating process for FishBase with kind assistance from Ruud Altenburg.</p>
<p>&#8226; Additional cleanings in The Reptile Database.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 26th August 2016</p>

<p class="field_header">40 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Spider Catalog</p>
<p>&#8226; Scarabs database</p>
<p>&#8226; The Reptile Database <i>(draft version)</i></p>
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>






<p class="iyb-slogan">In the Catalogue of Life, 28th July 2016</p>

<p class="field_header">41 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; AphidSF</p>
<p>&#8226; OrthopteraSF</p>
<p>&#8226; World Ferns <i>(second update in a year cycle)</i></p>
<p>&#8226; World Plants <i>(second update in a year cycle)</i></p>
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 27th June 2016</p>

<p class="field_header">49 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ChrysididaeSF</p> 
<p>&#8226; CockroachSF</p> 
<p>&#8226; CoreoideaSF</p> 
<p>&#8226; DermapteraSF</p> 
<p>&#8226; EmbiopteraSF</p> 
<p>&#8226; GrylloblattodeaSF</p> 
<p>&#8226; MantophasmatodeaSF</p> 
<p>&#8226; MantodeaSF</p> 
<p>&#8226; PhasmidaSF</p> 
<p>&#8226; PlecopteraSF</p> 
<p>&#8226; PsocodeaSF</p> 
<p>&#8226; ZorapteraSF</p> 
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 26th May 2016</p>

<p class="field_header">There is a new taxonomic checklist:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ITIS Global: phylum Hemichordata. ITIS data have replaced URMO Hemichordata.</p> 
</div>
<p>&nbsp;</p>

<p class="field_header">39 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ITIS Global: classes Aves and Mammalia; order Branchiobdellida (Annelida - Clitellata); family Histeridae (Insecta - Coleoptera)</p> 
<p>&#8226; ITIS Regional: superfamilies Cleroidea, Chrysomeloidea, Cucujoidea, Lymexyloidea, Tenebrionoidea and Coccinelloidea (Insecta - Coleoptera)</p>
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 28th April 2016</p>

<p class="field_header">39 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Ferns</p> 
<p>&#8226; World Plants</p>
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the 2016 Annual Checklist<br><span style="font-weight:normal">(1st April 2016)</span></p>

<p class="field_header">There are 12 new databases plus new global sectors from ITIS and World Plants: </p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Curculio: subfamily Entiminae (Curculionidae). This database has replaced WTaxa genera in subfamily Entiminae <i>(two updates in a year cycle)</i>.</p>
<p>&#8226; Brentids: Brentidae of the World. This database has replaced WTaxa Brentidae family in the CoL.</p>
<p>&#8226; ChrysididaeSF.</p>
<p>&#8226; Fauna Europaea, subphylum Turbellaria (Platyhelminthes) contributed data in the CoL proto-GSD for Platyhelminthes.</p>
<p>&#8226; GrylloblattodeaSF. This database has replaced ITIS data.</p>
<p>&#8226; ITIS Global, kingdoms Archaea and Bacteria. ITIS data have replaced Archaea and Bacteria previously received from BIOS.</p>
<p>&#8226; ITIS Global: phylum Acanthocephala. ITIS data have replaced proto-GSD for Acanthocephala.</p>
<p>&#8226; MantophasmatodeaSF. This database has replaced ITIS data.</p>
<p>&#8226; PBI Plant Bug: On-line Systematic Catalog of Plant Bugs (Insecta: Heteroptera: Miridae)</p>
<p>&#8226; The Scorpion Files.</p>
<p>&#8226; The World List of Cycads, online edition. This original database has replaced its old copy received via IOPI Global Plant Checklist in 2004.</p>
<p>&#8226; World Plants: selected Caryophyllales families and Astragalus. New sectors have replaced data from SCaDs and ILDIS.</p>
<p>&#8226; WSC: World Spider Catalog. This database has replaced old version of SpidCat and SalticidDB <i>(two updates in a year cycle)</i>.</p>
<p>&#8226; WWW: World Wide Wattle. This database replaced ILDIS Acacia checklist with modern classification of acacias <i>(two updates in a year cycle)</i>.</p>
<p>&#8226; ZorapteraSF. This database has replaced ITIS data.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">80 databases have been updated in a year cycle: </p>
<div style='margin-left: 10px;'>

<p>&#8226; 3i Cicadellinae</p>
<p>&#8226; 3i Cicadoidea</p>
<p>&#8226; 3i Typhlocybinae</p>
<p>&#8226; AphidSF</p>
<p>&#8226; Brachiopoda Database</p>
<p>&#8226; CockroachSF </p>
<p>&#8226; COOL</p>
<p>&#8226; CoreoideaSF</p>
<p>&#8226; DermapteraSF</p>
<p>&#8226; Dothideomycetes</p>
<p>&#8226; EmbiopteraSF</p>
<p>&#8226; FishBase <i>(two updates in a year cycle)</i></p>
<p>&#8226; FLOW</p>
<p>&#8226; Glomeromycota</p>
<p>&#8226; ICTV/MSL</p>
<p>&#8226; ITIS Global: families Calomyscidae, Cricetidae, Muridae, Nesomyidae, Platacanthomyidae and Spalacidae (Mammalia); order Passeriformes (Aves)</p>
<p>&#8226; ITIS Regional: order Branchiobdellida (Annelida - Clitellata) and families Buprestidae, Elmidae & Nitidulidae (Arthropoda - Insecta - Coleoptera)</p>
<p>&#8226; Lace Bugs Database</p>
<p>&#8226; LIAS </p>
<p>&#8226; MantodeaSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; Microsporidia</p>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; OrthopteraSF</p>
<p>&#8226; PhasmidaSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; Phoronida Database</p>
<p>&#8226; Phyllachorales</p>
<p>&#8226; PlecopteraSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; PsocodeaSF <i>(two updates in a year cycle)</i></p>
<p>&#8226; Psyl'list</p>
<p>&#8226; Rhytismatales </p>
<p>&#8226; Saccharomycetes </p>
<p>&#8226; Scarabs database <i>(two updates in a year cycle)</i></p>
<p>&#8226; Species Fungorum </p>
<p>&#8226; Sterpsiptera Database</p>
<p>&#8226; The White-Files</p>
<p>&#8226; TITAN (draft view)</p>
<p>&#8226; Trichomycetes</p>
<p>&#8226; World Ferns <i>(three updates in a year cycle)</i></p>
<p>&#8226; World Plants <i>(three updates in a year cycle)</i></p>
<p>&#8226; Xylariaceae</p>
<p>&#8226; Zygomycetes</p>
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates <i>(twelve updates in a year cycle)</i></p>
</div>
<p>&nbsp;</p>

<p class="field_header">Changes in management classification: </p>
<div style='margin-left: 10px;'>

<p>&#8226; <b>Plantae</b>. Four phyla without child taxa have been added in the classification: Glaucophyta, Rhodophyta, Chlorophyta and Charophyta. Two classes Anthocerotopsida and Leiosporocerotopsida have been placed in phylum Anthocerotophyta; three classes Haplomitriopsida, Jungermanniopsida and Marchantiopsida have been placed in phylum Marchantiophyta. CoL classification for flowering plants has been adjusted (where it was appropriate) to P.F.Stevens (2001-2015), Angiosperm Phylogeny Website, version 12, July 2012 at <a href = "http://www.mobot.org/MOBOT/research/APweb"  target = "_blank">www.mobot.org/MOBOT/research/APweb</a>.</p>
<p>&#8226; <b>Chromista</b>. Three phyla without child taxa have been added: Cryptista, Haptophyta, and Ochrophyta. Phyla Ciliophora and Cercozoa have been placed in Chromista. Class Conoidasida has been placed in phylum Miozoa.</p>
<p>&#8226; <b>Protozoa</b>. Four phyla without child taxa have been added: Euglenozoa, Loukozoa, Metamonada and Sulcozoa. Class Lobosa has been placed in phylum Amoebozoa.</p>
<p>&#8226; <b>Animalia</b>. Phylum Kamptozoa has been returned to Entoprocta. </p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other changes: </p>
<div style='margin-left: 10px;'>

<p>&#8226; ITIS has requested to rebrand two its checklists in the Catalogue (superfamily Ceraphronoidea and family Formicidae in Hymenoptera) from "regional" to "global".</p>
<p>&#8226; Two databases (Brachiopoda Database and Phoronida Database) have requested to become independent from WoRMS.</p>
<p>&#8226; Additional cleanings and corrections have been done in TITAN, ApidSF, ITIS, ILDIS, Strepsiptera Database, World Plants and WCSP data. </p>
<p>&#8226; 8 WoRMS checklists have been added in automated process of monthly updates by Luisa Abucay and Ruud Altenburg in July 2015.</p>
<p>&#8226; Rules in export scripts and automated templates for WoRMS checklists have been revised and improved by Bart Vanhoorne, Ruud Altenburg and Luisa Abucay</p>
<p>&#8226; New version of user interface (v1.9 r1549) was deployed on 23rd June 2015. New interface displays extinct taxa, subgenera in species names, and it uses stable keys in URLs. Many bugs were fixed in a new version.</p>
<p>&#8226; Extinct taxa and fossils are allowed in the Catalogue since March 2015.</p>
<p>&#8226; New field "Bibliographic Citation", as standard reference to supplier database, has been added on each Species Details and Database Details pages and in webservice. Bibliographic Citations are identical to those which appear in a chapter "How to cite this work".</p>
<p>&#8226; Figures for species estimates have been added with selected taxa of various ranks. This is a pilot trial for introducing estimates for species globally recognised by taxonomists. Estimates are based on personal knowledge of database authors or on previously published data.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 25th March 2016</p>

<p class="field_header">41 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Cicadellinae</p> 
<p>&#8226; 3i Cicadoidea</p>
<p>&#8226; 3i Typhlocybinae</p>
<p>&#8226; FishBase <i>(second update in a year cycle)</i></p>
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other changes:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Additional cleanings through whole database.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 27th February 2016</p>

<p class="field_header">51 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; LIAS</p>
<p>&#8226; Dothideomycetes</p>
<p>&#8226; Glomeromycota</p>
<p>&#8226; Phyllachorales</p> 
<p>&#8226; Rhytismatales</p> 
<p>&#8226; Saccharomycetes</p> 
<p>&#8226; Species Fungorum</p> 
<p>&#8226; Trichomycetes</p> 
<p>&#8226; Xylariaceae</p>
<p>&#8226; Zygomycetes</p>
<p>&#8226; World Wide Wattle <i>(second update in a year cycle)</i></p>
<p>&#8226; World Spider Catalog <i>(second update in a year cycle)</i></p>
<p>&#8226; 3i Curculio <i>(second update in a year cycle)</i></p>
<p>&#8226; Scarabs database <i>(second update in a year cycle)</i></p>
<p>&#8226; 37 WoRMS checklists have been updated through automated process using CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other changes:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Two databases, Brachiopoda Database and Phoronida Database, have requested to become independent from WoRMS.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 29th January 2016</p>

<p class="field_header">There is one new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; PBI Plant Bug: On-line Systematic Catalog of Plant Bugs (Insecta: Heteroptera: Miridae)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">51 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; Microsporidia</p>
<p>&#8226; AphidSF</p>
<p>&#8226; CockroachSF</p>
<p>&#8226; CoreoideaSF</p>
<p>&#8226; DermapteraSF</p>
<p>&#8226; EmbiopteraSF</p>
<p>&#8226; MantodeaSF</p>
<p>&#8226; OrthopteraSF</p>
<p>&#8226; PhasmidaSF</p>
<p>&#8226; PlecopteraSF</p>
<p>&#8226; PsocodeaSF</p>
<p>&#8226; 39 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Further adjustments between WTaxa and 3i Curculio have been applied.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 23rd December 2015</p>

<p class="field_header">There are 6 new taxonomic databases:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Curculio: subfamily Entiminae (Curculionidae). This database has replaced WTaxa genera in subfamily Entiminae</p>
<p>&#8226; ITIS Global: phylum Acanthocephala. ITIS data have replaced proto-GSD for Acanthocephala</p>
<p>&#8226; ChrysididaeSF</p>
<p>&#8226; GrylloblattodeaSF. This database has replaced ITIS data</p>
<p>&#8226; MantophasmatodeaSF. This database has replaced ITIS data</p>
<p>&#8226; ZorapteraSF. This database has replaced ITIS data</p>
</div>
<p>&nbsp;</p>

<p class="field_header">40 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Plants <i>(third update in a year cycle)</i></p>
<p>&#8226; 39 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; CoL classification for flowering plants has been adjusted (where it was appropriate) to P.F.Stevens (2001-2015), Angiosperm Phylogeny Website, version 12, July 2012 at <a href = "http://www.mobot.org/MOBOT/research/APweb"  target = "_blank">www.mobot.org/MOBOT/research/APweb</a></p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 20th November 2015</p>

<p class="field_header">43 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ICTV/MSL</p>
<p>&#8226; Order Passeriformes (Chordata - Aves) in ITIS Global</p>
<p>&#8226; Order Branchiobdellida (Annelida - Clitellata) and family Buprestidae (Arthropoda - Insecta - Coleoptera) in ITIS Regional</p>
<p>&#8226; World Ferns <i>(third update in a year cycle)</i></p>
<p>&#8226; 39 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Classification inconsistency in Bigyra/Labyrinthista has been fixed after notification from Paul Kirk.</p>
<p>&#8226; New field "Bibliographic Citation", as standard reference to supplier database, has been added on each Species Details page and in webservice. Bibliographic Citations are identical to those which appear in a chapter "How to cite this work".</p>
<p>&#8226; A bug in presentation of species estimates has been fixed.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 27th October 2015</p>

<p class="field_header">42 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Caryophyllales families from SCaDs database have been replaced with World Plants checklists</p>
<p>&#8226; Families Elmidae & Nitidulidae in ITIS Regional</p>
<p>&#8226; Families Calomyscidae, Cricetidae, Muridae, Nesomyidae, Platacanthomyidae and Spalacidae (class Mammalia) in ITIS Global</p>
<p>&#8226; 39 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Additional cleanings and corrections have been done in TITAN, ApidSF, ITIS, ILDIS, Strepsiptera Database, World Plants and WCSP data.</p>
<p>&#8226; 7 proto-GSDs with participation of WoRMS Acanthocephala, Cestoda, Mollusca, Monogenea, Myxozoa, Proseriata-Kalyptorhyncha and Trematoda have been re-deployed.</p>
<p>&#8226; Figures for estimated species have been added with selected Animalia and Plantae taxa of various ranks. This is a pilot trial for introducing estimates for species recognised in each group worldwide by taxonomists at current stage of science. The estimates are based on personal knowledge of database authors or on previously published data. Estimate figures will be emendated from one release to another according to the best available knowledge.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 28th September 2015</p>

<p class="field_header">42 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; FishBase</p>
<p>&#8226; World Ferns <i>(second update in a year cycle)</i></p>
<p>&#8226; World Plants. ILDIS genera Astragalus and Astracantha have been replaced with World Plants' modern classification of Astragalus s.l. group.</p>
<p>&#8226; 39 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Changes in management classification:</p>
<div style='margin-left: 10px;'>
<p>&#8226; <b>Plantae.</b> 4 phyla without child taxa have been added in the classification: Glaucophyta, Rhodophyta, Chlorophyta and Charophyta. 2 classes Anthocerotopsida and Leiosporocerotopsida have been placed in phylum Anthocerotophyta; 3 classes Haplomitriopsida, Jungermanniopsida and Marchantiopsida have been placed in phylum Marchantiophyta.</p>
<p>&#8226; <b>Chromista.</b> 3 phyla without child taxa have been added: Cryptista, Haptophyta, and Ochrophyta. Phyla Ciliophora and Cercozoa have been placed in Chromista. Class Conoidasida has been placed in phylum Miozoa.</p>
<p>&#8226; <b>Protozoa.</b> 4 phyla without child taxa have been added: Euglenozoa, Loukozoa, Metamonada and Sulcozoa. Class Lobosa has been placed in phylum Amoebozoa.</p>
<p>&#8226; <b>Animalia.</b> Phylum Kamptozoa has been returned to Entoprocta.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Rules in export scripts and automated templates for WoRMS checklists have been revised and improved by Bart Vanhoorne, Ruud Altenburg and Luisa Abucay.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 26th August 2015</p>

<p class="field_header">There is one taxonomic database from a new provider:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WSC: World Spider Catalog <i>(In 2014, world's known "SpidCat: The World Spider Catalog" by N.I. Platnick & R.J. Raven has successfully migrated to a new host at Natural History Museum of Bern, Switzerland. The catalogue was transformed into relational database with truly international editorial team led by C. Rheims, C. Kropf, P. J&auml;ger, T. Blick & H. Ono. New WSC has replaced old version of SpidCat and SalticidDB).</i></p>
</div>
<p>&nbsp;</p>

<p class="field_header">41 database have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Scarabs database</p>
<p>&#8226; TITAN (<i>draft view</i>)</p>
<p>&#8226; 39 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Further cleanings have been applied in The Scorpion Files</p>
<p>&#8226; Direct links to original Fauna Europaea species pages have been added with 237 turbellarian species</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Recognized problems:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Cerambycidae checklist from TITAN may have integrity problems with its data. Further cleanings will be continued in September.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 30th July 2015</p>

<p class="field_header">There are two new taxonomic checklists:</p>
<div style='margin-left: 10px;'>
<p>&#8226; The Scorpion Files (<i>Data have been harvested from Jan Ove Rein's website in cooperation with Encyclopedia of Life team</i>)</p>
<p>&#8226; Fauna Europaea, subphylum Turbellaria (Platyhelminthes) contributed data in the CoL proto-GSD for Platyhelminthes. (<i>We are very grateful to Yde de Jong, Fauna Europaea Editor for his kind efforts to make it possible. Conceptual integration was completed by Thomas Kunze).</i></p>
</div>
<p>&nbsp;</p>

<p class="field_header">43 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; DermapteraSF</p>
<p>&#8226; PhasmidaSF</p>
<p>&#8226; PsocodeaSF</p>
<p>&#8226; FLOW</p>
<p>&#8226; 39 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Recognized problems:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Due to updates in automated templates, some WoRMS checklists may have temporary bugs, which will be dynamically fixed in next few weeks.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>





<p class="iyb-slogan">In the Catalogue of Life, 23rd June 2015</p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; The World List of Cycads, online edition. This original database has replaced its old copy, which CoL received via IOPI Global Plant Checklist in 2004</p>

</div>
<p>&nbsp;</p>

<p class="field_header">35 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; EmbiopteraSF</p>
<p>&#8226; MantodeaSF</p>
<p>&#8226; PlecopteraSF</p>
<p>&#8226; World Ferns</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ITIS requested to rebrand two checklists (family Formicidae and superfamily Ceraphronoidea, Hymenoptera) from "regional" to "global"</p>
<p>&#8226; New version of user interface was deployed (v1.9 r1549). New interface displays extinct taxa, subgenera in species names and uses stable keys in URLs. Many bugs were fixed in this version</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 18th May 2015</p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WWW: World Wide Wattle. This database has replaced ILDIS Acacia checklist with modern classification of acacias</p>

</div>
<p>&nbsp;</p>

<p class="field_header">34 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; COOL</p>
<p>&#8226; Psyl'list</p>
<p>&#8226; The White-Files</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Recognized problem:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Species Files and Scarabs databases in the CoL contain fossil taxa now, but these taxa are not marked in current version of user interface</p>
<p>&#8226; Software continues withdrawing subgenera in species names and creating duplicated names</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 21st April 2015</p>

<p class="field_header">There is a new taxonomic database and new global checklist from ITIS:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Brentids: Brentidae of the world. This database has replaced WTaxa Brentidae family in the CoL.</p>
<p>&#8226; ITIS Global, kingdoms Archaea and Bacteria. ITIS data have replaced Archaea and Bacteria previously received from BIOS.</p>

</div>
<p>&nbsp;</p>

<p class="field_header">33 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Sterpsiptera Database</p>
<p>&#8226; Lace Bugs Database</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Recognized problem:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Species Files and Scarabs databases in the CoL contain fossil taxa now, but these taxa are not marked in current version of user interface</p>
<p>&#8226; Software continues withdrawing subgenera in species names and creating duplicated names</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the 2015 Annual Checklist<br><span style="font-weight:normal">(1st April 2015)</span></p>

<p class="field_header">There are 12 new databases, plus new global sector from ITIS: </p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Cicadoidea</p>
<p>&#8226; FADA Copepoda <I>(fresh water taxa in CoL proto-GSD)</I></p>
<p>&#8226; DermapteraSF</p>
<p>&#8226; ITIS Global, family Lampyridae (Coleoptera) </p>
<p>&#8226; WoRMS Acanthocephala <I> (marine taxa in CoL proto-GSD)</I></p>
<p>&#8226; WoRMS Acoelomorpha</p>
<p>&#8226; WoRMS Cephalochordata</p>
<p>&#8226; WoRMS Foraminifera</p>
<p>&#8226; WoRMS Kinorhyncha</p>
<p>&#8226; WoRMS Merostomata</p>
<p>&#8226; WoRMS Octocorallia</p>
<p>&#8226; WoRMS Orthonectida</p>
<p>&#8226; WoRMS Rhombozoa (phylum Dicyemida) </p>
</div>
<p>&nbsp;</p>

<p class="field_header">72 databases have been updated in a year cycle: </p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Cicadellinae</p>
<p>&#8226; 3i Typhlocybinae</p>
<p>&#8226; AphidSF</p>
<p>&#8226; CockroachSF <I>(new name for BlattodeaSF)</I></p>
<p>&#8226; Conifer Database</p>
<p>&#8226; COOL</p>
<p>&#8226; CoreoideaSF</p>
<p>&#8226; Dothideomycetes</p>
<p>&#8226; EmbiopteraSF</p>
<p>&#8226; FishBase <I>(two updates in a year cycle)</I></p>
<p>&#8226; FLOW</p>
<p>&#8226; GCC</p>
<p>&#8226; Glomeromycota</p>
<p>&#8226; ICTV/MSL</p>
<p>&#8226; ILDIS has absorbed "ILDIS for i4Life" checklist</p>
<p>&#8226; ITIS Global, class Mammalia; family Parulidae & genus Oceanodroma (Aves) <I>(two updates in a year cycle)</I></p>
<p>&#8226; ITIS Regional, superfamily Idiostoloidea (Hemiptera, N. America), family Elmidae (Coleoptera, N. America) and species Leucochloridiomorpha constantiae (Trematoda) <I>(two updates in a year cycle)</I></p>
<p>&#8226; MantodeaSF</p>
<p>&#8226; Microsporidia</p>
<p>&#8226; OrthopteraSF</p>
<p>&#8226; PhasmidaSF</p>
<p>&#8226; Phyllachorales</p>
<p>&#8226; PlecopteraSF <I>(two updates in a year cycle)</I></p>
<p>&#8226; PsocodeaSF</p>
<p>&#8226; Psyl'list</p>
<p>&#8226; Rhytismatales</p>
<p>&#8226; Saccharomycetes</p>
<p>&#8226; Scarabs database <I>(two updates in a year cycle)</I></p>
<p>&#8226; Species Fungorum</p>
<p>&#8226; SpidCat via ITIS</p>
<p>&#8226; Strepsiptera Database</p>
<p>&#8226; The White-Flies</p>
<p>&#8226; Trichomycetes</p>
<p>&#8226; World Checklist of Selected Plant Families</p>
<p>&#8226; World Ferns <I>(five updates in a year cycle)</I></p>
<p>&#8226; World Plants <I>(five updates in a year cycle)</I></p>
<p>&#8226; WoRMS Octocorallia <I>(two updates in a year cycle)</I></p>
<p>&#8226; WoRMS Orthonectida <I>(two updates in a year cycle)</I></p>
<p>&#8226; WoRMS Rhombozoa <I>(two updates in a year cycle)</I></p>
<p>&#8226; Xylariaceae</p>
<p>&#8226; Zygomycetes</p>
<p>&#8226; 31 WoRMS checklists were updated every month through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements: </p>
<div style='margin-left: 10px;'>
<p>&#8226; "ILDIS for i4Life" checklist was integrated in main ILDIS database</p>
<p>&#8226; WCSP Ebenaceae checklist has replaced EbenaBase</p>
<p>&#8226; World Plants have replaced World Umbellifer Database and MELnet</p>
<p>&#8226; WoRMS checklists have replaced selected URMO taxa</p>
<p>&#8226; Additional cleanings on request from data providers and users have been undertaken</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>  



<p class="iyb-slogan">In the Catalogue of Life, 18th March 2015</p>

<p class="field_header">There is a new global taxonomic checklist from ITIS:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ITIS Global: Family Lampyridae from order Coleoptera</p>

</div>
<p>&nbsp;</p>

<p class="field_header">14 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Cicadellinae</p>
<p>&#8226; 3i Typhlocybinae</p>
<p>&#8226; ITIS Global: families Gliridae, Dipodidae, Anomaluridae and genus Callosciurus from Mammalia; superfamily Idiostoloidea from Heteroptera</p>
<p>&#8226; Scarabs database <I>(second update in a year cycle)</I></p>
<p>&#8226; 10 Species Files were re-assembled (AphidSF, CockroachSF, CoreoideaSF, DermapteraSF, EmbiopteraSF, MantodeaSF, OrthopteraSF, PhasmidaSF, PlecopteraSF and PsocodeaSF)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Additional cleanings for duplicated names in Plantae databases</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Recognized problem:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Scarabs and Species Files (SF) databases contain fossil taxa now, but these taxa are not marked in current version of user interface</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 15th February 2015</p>

<p class="field_header">There are two new taxonomic databases:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WoRMS Acanthocephala. WoRMS contributed marine taxa in CoL proto-GSD</p>
<p>&#8226; FADA Copepoda. FADA contributed fresh water taxa in CoL proto-GSD</p>

</div>
<p>&nbsp;</p>

<p class="field_header">33 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Plants <I>(fifth update in a year cycle)</I>. Global World Plants checklists for families Apiaceae and Melastomataceae has replaced World Umbellifer Database and Melastomataceae.Net</p>
<p>&#8226; World Ferns <I>(fifth update in a year cycle)</I></p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; All missing common names in release of January are now brought back</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Recognized problem:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Species Files (SF) databases in the CoL include fossil taxa now, but these taxa are not marked in current version of user interface</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 30th January 2015</p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; DermapteraSF</p>
</div>
<p>&nbsp;</p>

<p class="field_header">42 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; AphidSF</p>
<p>&#8226; CockroachSF <I>(new name for BlattodeaSF)</I></p>
<p>&#8226; CoreoideaSF</p>
<p>&#8226; EmbiopteraSF</p>
<p>&#8226; MantodeaSF</p>
<p>&#8226; OrthopteraSF</p>
<p>&#8226; PhasmidaSF</p>
<p>&#8226; PlecopteraSF</p>
<p>&#8226; PsocodeaSF</p>
<p>&#8226; FishBase <I>(second update in a year cycle)</I></p>
<p>&#8226; World Ferns <I>(fourth update in a year cycle)</I></p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; SpidCat: distribution data have been retrieved from database version of January 2008</p>
<p>&#8226; Additional cleanings for duplicated names in Animalia databases</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Recognized problem:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Species Files (SF) databases in the CoL include fossil taxa now, but these taxa are not marked in current version of user interface</p>
<p>&#8226; Over 240K of common names are missing in this release</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>







<p class="iyb-slogan">In the Catalogue of Life, 22nd December 2014</p>

<p class="field_header">34 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Cicadoidea<I> (second update in a year cycle)</I></p>
<p>&#8226; World Ferns<I> (third update in a year cycle)</I></p>
<p>&#8226; World Plants<I> (fourth update in a year cycle)</I></p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 24th November 2014</p>

<p class="field_header">There are two new taxonomic databases:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 3i Cicadoidea</p>
<p>&#8226; WoRMS Foraminifera</p>
</div>
<p>&nbsp;</p>

<p class="field_header">4 new WoRMS checklists have replaced old URMO sectors:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WoRMS Acoelomorpha</p>
<p>&#8226; WoRMS Cephalochordata</p>
<p>&#8226; WoRMS Kinorhyncha</p>
<p>&#8226; WoRMS Merostomata</p>
</div>
<p>&nbsp;</p>

<p class="field_header">35 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Ferns <I>(second update in a year cycle)</I></p>
<p>&#8226; WoRMS Octocorallia <I>(second update in a year cycle)</I></p>
<p>&#8226; WoRMS Orthonectida <I>(second update in a year cycle)</I></p>
<p>&#8226; WoRMS Rhombozoa <I>(second update in a year cycle)</I></p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Additional cleanings on request from data providers and users</p> 
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 29th October 2014</p>

<p class="field_header">36 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WCSP: World Checklist of Selected Plant Families; WCSP Ebenaceae checklist has replaced EbenaBase in October edition</p>
<p>&#8226; World Plants <i>(third update in a year cycle)</i></p>
<p>&#8226; ITIS Global (class Mammalia; family Parulidae & genus Oceanodroma (Aves)</p>
<p>&#8226; SpidCat via ITIS (order Araneae, excl. SalticidDB; some common names were added)</p>
<p>&#8226; ITIS Regional (family Elmidae (Coleoptera, N.America) and species Leucochloridiomorpha constantiae (Trematoda))</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Flowering plant checklists have been disambiguated</p> 
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>








<p class="iyb-slogan">In the Catalogue of Life, 19th September 2014</p>

<p class="field_header">33 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Scarabs database</p>
<p>&#8226; World Plants <i>(second update in a year cycle)</i></p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Author strings with type trinomials in plant taxa have been corrected according general practice in botanical nomenclature</p>
<p>&#8226; Further fixes were completed for World Ferns and Conifer Database</p> 
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 22nd August 2014</p>

<p class="field_header">33 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Conifer Database</p>
<p>&#8226; World Ferns. Main editorial transformations and data assembly have been completed via CoL Workbench templates with additional manual data cleanings</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Plant family Solanaceae: duplicated names from regional data sets were removed</p>
<p>&#8226; CoL database passed additional technical cleanings</p> 
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>




<p class="iyb-slogan">In the Catalogue of Life, 29th July 2014</p>

<p class="field_header">One new WoRMS checklist has replaced old URMO sector:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WoRMS Octocorallia</p>
</div>
<p>&nbsp;</p>

<p class="field_header">33 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; GCC</p>
<p>&#8226; FishBase</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 28th June 2014</p>

<p class="field_header">2 new WoRMS checklists have replaced old URMO sectors:</p>
<div style='margin-left: 10px;'>
<p>&#8226; WoRMS Orthonectida</p>
<p>&#8226; WoRMS Rhombozoa (phylum Dicyemida)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">37 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; FLOW</p>
<p>&#8226; COOL</p>
<p>&#8226; Psyl'list</p>
<p>&#8226; Strepsiptera Database</p>
<p>&#8226; The White-Flies</p>
<p>&#8226; World Plants</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Accepted names and synonyms passed additional cleanings in the database.</p>
</div>
<p>&nbsp;</p>


<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 30th May 2014</p>

<p class="field_header">42 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ICTV/MSL</p>
<p>&#8226; Dothideomycetes</p>
<p>&#8226; Glomeromycota</p>
<p>&#8226; Microsporidia</p>
<p>&#8226; Phyllachorales</p>
<p>&#8226; Rhytismatales</p>
<p>&#8226; Saccharomycetes</p>
<p>&#8226; Species Fungorum</p>
<p>&#8226; Trichomycetes</p>
<p>&#8226; Xylariaceae</p>
<p>&#8226; Zygomycetes</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; <I>ILDIS for i4Life</I> checklist was integrated in main ILDIS database.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Recognized problems:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Duplicates and classification clashes are possible between LIAS and updated fungi databases in this edition.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 28th April 2014</p>

<p class="field_header">32 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; PlecopteraSF</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the 2014 Annual Checklist<br><span style="font-weight:normal">(1st April 2014)</span></p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; CarabCat: Global database of ground beetles*</p>
<p>&#8226; FADA Cladocera</p>
<p>&#8226; FADA Halacaridae</p>
<p>&#8226; GloBIS family Lycaenidae*</p>
<p>&#8226; HymIS families Crabronidae and Pompilidae*</p>
<p>&#8226; ILDIS for i4Life*</p>
<p>&#8226; ITIS Global family Cactaceae </p>
<p>&#8226; Lace Bugs Database*</p>
<p>&#8226; Microsporidia</p>
<p>&#8226; SCaDs: Selected Caryophyllales Databases*</p>
<p>&#8226; Scarabs family Lucanidae*</p>
<p>&#8226; Tessaratomid Database*</p>
<p>&#8226; The White-Files*</p>
<p>&#8226; World Ferns</p>
<p>&#8226; World Plants</p>
* <I>delivery of i4Life pilot project</I>
</div>
<p>&nbsp;</p>

<p class="field_header">56 databases have been updated in a year cycle, 33 of them updated every month via automated CoL Workbench (WoRMS, World Ferns & World Plants) and 4 updated more than once via manual assembly process:</p>
<div style='margin-left: 10px;'>
<p>&#8226; AnnonBase</p>
<p>&#8226; BdelloideaBase</p>
<p>&#8226; CCW: Catalogue of Craneflies of the World</p>
<p>&#8226; ChenoBase</p>
<p>&#8226; Conifer Database</p>
<p>&#8226; Dothideomycetes</p>
<p>&#8226; EbenaBase </p>
<p>&#8226; FishBase</p>
<p>&#8226; GCC: Global Compositae Checklist </p>
<p>&#8226; Glomeromycota</p>
<p>&#8226; ITIS Global </p>
<p>&#8226; LDL Neuropterida</p>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; Phyllachorales</p>
<p>&#8226; Rhytismatales</p>
<p>&#8226; Saccharomycetes</p>
<p>&#8226; Scarabs</p>
<p>&#8226; Species Fungorum</p>
<p>&#8226; SysMyr</p>
<p>&#8226; The Reptile Database</p>
<p>&#8226; Trichomycetes</p>
<p>&#8226; World Ferns</p>
<p>&#8226; World Plants</p>
<p>&#8226; Xylariaceae</p>
<p>&#8226; Zygomycetes</p>
<p>&#8226; 31 WoRMS checklists</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; New version of the Annual Checklist interface now shows subgenera as a part of species names in some zoological databases. </p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 17th March 2014</p>

<p class="field_header">34 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Ferns (fourth update in a year cycle). All editorial transformations and data assembly have been completed via CoL Workbench templates</p>
<p>&#8226; World Plants (fifth update in a year cycle). Editorial transformations and data assembly have been partly completed via CoL Workbench templates and partly by manual process</p>
<p>&#8226; ITIS Global (orders Passeriformes, Perissodactyla, Zoraptera and families Dasyuridae & Sciuridae)</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 26th February 2014</p>

<p class="field_header">35 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Plants added 103 new global checklists for flowering plants (fourth update in a year cycle). Editorial transformations and data assembly have been partly completed via CoL Workbench templates and partly by manual process</p>
<p>&#8226; AnnonBase (delivery of i4Life pilot project)</p>
<p>&#8226; ChenoBase (delivery of i4Life pilot project)</p>
<p>&#8226; EbenaBase (delivery of i4Life pilot project)</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Apology:</p>
<div style='margin-left: 10px;'>
<p>&#8226; There are few cases of genera misplacements in families of Magnoliopsida detected at very last minute. The issues will be fixed in the next release.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 20th January 2014</p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Microsporidia: Unicellular spore-forming protozoan parasites</p>
</div>
<p>&nbsp;</p>

<p class="field_header">33 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Nomen.eumycetozoa.com</p>
<p>&#8226; World Ferns (third update in a year cycle). All editorial transformations and data assembly have been completed via CoL Workbench templates</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>



<p class="iyb-slogan">In the Catalogue of Life, 10th December 2013</p>

<p class="field_header">New global checklists have been added in two databases:</p>
<div style='margin-left: 10px;'>
<p>&#8226; HymIS families Crabronidae and Pompilidae (deliveries of i4Life pilot projects)</p>
<p>&#8226; GloBIS family Lycaenidae (delivery of i4Life pilot project)</p>

</div>
<p>&nbsp;</p>

<p class="field_header">31 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; SCaDs references have been added</p>
<p>&#8226; Few fixes in LDL Neuropterida</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 19th November 2013</p>

<p class="field_header">There are two new taxonomic databases:</p>
<div style='margin-left: 10px;'>
<p>&#8226; CarabCat: Global database of ground beetles by Wolfgang Lorenz 
(delivery of i4Life pilot project)</p>
<p>&#8226; SCaDs: Selected Caryophyllales Databases by Magda Sitko, Alastair Culham & al. (delivery of i4Life pilot project)</p>

</div>
<p>&nbsp;</p>

<p class="field_header">34 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Ferns (second update in a year cycle). All editorial transformations and data assembly have been completed via CoL Workbench templates</p>
<p>&#8226; World Plants added 73 new global checklists for flowering plants (third update in a year cycle). World Plants Rosaceae checklist has replaced IOPI Rosaceae. (All editorial transformations and data assembly have been completed via CoL Workbench templates)</p>
<p>&#8226; LDL Neuropterida</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>





<p class="iyb-slogan">In the Catalogue of Life, 17th October 2013</p>

<p class="field_header">There is one new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ILDIS for i4Life: additional taxa. (This dataset was created as a delivery of i4Life pilot project. It contains new species, which are complementing ILDIS checklist. In next few years, this dataset will be assimilated in ILDIS database).</p>

</div>
<p>&nbsp;</p>

<p class="field_header">One database has been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Plants added 26 new global checklists for flowering plants (second update in a year cycle). All editorial transformations and assembly have been completed via CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>





<p class="iyb-slogan">In the Catalogue of Life, 24th September 2013</p>

<p class="field_header">There are 4 new taxonomic databases:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Plants by Michael Hassler</p>
<p>&#8226; Lace Bugs Database by Eric Guilbert (delivery of i4Life pilot project)</p>
<p>&#8226; Tessaratomid Database by Philippe Magnien (delivery of i4Life pilot project)</p>
<p>&#8226; The White-Files by Jon Martin & David Ouvrard (delivery of i4Life pilot project)</p>

</div>
<p>&nbsp;</p>

<p class="field_header">34 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Conifer Database</p>
<p>&#8226; Scarabs: World Scarabaeidae Database (delivery of i4Life pilot project)</p>
<p>&#8226; GCC: Global Compositae Checklist (second update in a year cycle)</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 15th August 2013</p>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; World Ferns by Michael Hassler. (Data were assembled by V. Didziulis via automated CoL Workbench templates)</p>

</div>
<p>&nbsp;</p>

<p class="field_header">41 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; BdelloideaBase</p>
<p>&#8226; Dothideomycetes *</p>
<p>&#8226; Glomeromycota *</p>
<p>&#8226; Phyllachorales *</p>
<p>&#8226; Rhytismatales *</p>
<p>&#8226; Saccharomycetes *</p>
<p>&#8226; Species Fungorum *</p>
<p>&#8226; Trichomycetes *</p>
<p>&#8226; Xylariaceae *</p>
<p>&#8226; Zygomycetes *</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
<I>Nine fungi databases (*) have been updated as a result of i4Life pilot project delivery.</I>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 22nd July 2013</p>

<p class="field_header">4 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; CCW: Catalogue of Craneflies of the World (delivery of i4Life pilot project)</p>
<p>&#8226; GCC: Global Compositae Checklist</p>
<p>&#8226; FishBase</p>
<p>&#8226; ITIS Global: families Castoridae, Geomyidae & Heteromyidae</p>

</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; UCD species URLs have been updated</p>
<p>&#8226; Global Gracillariidae: metadata have been updated. Database short name changed from World Gracillariidae to Global Gracillariidae</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 25th June 2013</p>

<p class="field_header">There is a new global taxonomic checklist from ITIS:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Family Cactaceae (Plantae – Tracheophyta – Magnoliopsida – Caryophyllales – <b>Cactaceae</b>)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">31 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other changes:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Genus Manota was moved to family Mycetophilidae on request of Systema Dipterorum editor</p>
<p>&#8226; All provisionally accepted species were taken off from family Rosaceae (IOPI-GPC)</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 23rd May 2013</p>

<p class="field_header">There are two new taxonomic databases:</p>
<div style='margin-left: 10px;'>
<p>&#8226; FADA Cladocera</p>
<p>&#8226; FADA Halacaridae</p>
</div>
<p>&nbsp;</p>

<p class="field_header">32 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; The Reptile Database (former TIGR Reptile Database)</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>


<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 18th April 2013</p>

<p class="field_header">34 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; SysMyr</p>
<p>&#8226; Scarabs</p>
<p>&#8226; BdelloideaBase</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates</p>
</div>
<p>&nbsp;</p>


<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the 2013 Annual Checklist<BR><span style="font-weight:normal">(1st April 2013)</span></p>

<p class="field_header">19 new databases plus new global sectors from ITIS have been added in a year cycle:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Catalogue of Life China</p>
<p>&#8226; CoreoideaSF: Coreoidea Species File</p>
<p>&#8226; FADA Bivalvia: World checklist of freshwater Bivalvia species</p>
<p>&#8226; FADA Ephemeroptera: World checklist of freshwater Ephemeroptera species</p> 
<p>&#8226; FADA Nematomorpha: World checklist of freshwater Nematomorpha species</p>
<p>&#8226; FADA Turbellaria: World checklist of freshwater Turbellaria species</p>
<p>&#8226; HymIS Rhopalosomatidae: Hymenoptera Information System, Rhopalosomatidae of the world</p>
<p>&#8226; ITIS Global (Plantae: families Barbeyaceae, Bataceae, Cephalotaceae, Crossosomataceae, Eucommiaceae, Gerrardinaceae, Koeberliniaceae, Lophopyxidaceae, Montiniaceae, Penthoraceae, Petenaeaceae, Pycnanthaceae, Rhoipteleaceae; Animalia: insect subfamily Cassidinae)</p>
<p>&#8226; MolluscaFW: World Checklist of Freshwater Mollusca</p>
<p>&#8226; PsocodeaSF: Psocodea Species File</p>
<p>&#8226; WoRMS Cestoda: World List of Cestoda*</p>
<p>&#8226; WoRMS Chaetognatha: World list of Chaetognatha*</p>
<p>&#8226; WoRMS Gastrotricha: World Gastrotricha Database*</p>
<p>&#8226; WoRMS Gnathostomulida: World list of Gnathostomulida*</p>
<p>&#8226; WoRMS Mollusca: World Marine Mollusca database</p>
<p>&#8226; WoRMS Monogenea: World list of Monogenea</p>
<p>&#8226; WoRMS Myxozoa: World list of Myxozoa</p>
<p>&#8226; WoRMS Placozoa: World Placozoa Database*</p>
<p>&#8226; WoRMS Priapulida: World list of Priapulida*</p>
<p>&#8226; WoRMS Trematoda: World list of Trematoda*<br />
</div>
<p>(*<i>WoRMS has replaced URMO sector</i>)</p>

<p>&nbsp;</p>

<p class="field_header">55 databases have been updated in a year cycle; 31 of them updated nine times via automated CoL Workbench (WoRMS) and 9 updated twice via manual assembly process:</p>
<div style='margin-left: 10px;'>
<p>&#8226; AphidSF</p>
<p>&#8226; BdelloideaBase</p>
<p>&#8226; BlattodeaSF</p>
<p>&#8226; EmbiopteraSF (two updates)</p>
<p>&#8226; FADA Rotifera</p>
<p>&#8226; FishBase (two updates)</p>
<p>&#8226; GCC </p>
<p>&#8226; GloBIS (GART)</p>
<p>&#8226; ICTV/MSL</p>
<p>&#8226; ILDIS (two updates)</p>
<p>&#8226; ITIS Regional (Tracheophyta)</p>
<p>&#8226; LepIndex </p>
<p>&#8226; LIAS (two updates)</p>
<p>&#8226; MantodeaSF</p>
<p>&#8226; MELnet </p>
<p>&#8226; OrthopteraSF (two updates)</p>
<p>&#8226; PhasmidaSF</p>
<p>&#8226; PlecopteraSF (two updates)</p>
<p>&#8226; RJB Geranium</p>
<p>&#8226; Scarabs (two updates)</p>
<p>&#8226; SpidCat via ITIS</p>
<p>&#8226; Strepsiptera Database</p>
<p>&#8226; SysMyr (three updates)</p>
<p>&#8226; WoRMS Asteroidea (9 updates)</p>
<p>&#8226; WoRMS Bochusacea (9 updates)</p>
<p>&#8226; WoRMS Brachiopoda (9 updates)</p>
<p>&#8226; WoRMS Brachypoda (9 updates)</p>
<p>&#8226; WoRMS Brachyura (9 updates)</p>
<p>&#8226; WoRMS Bryozoa (9 updates)</p>
<p>&#8226; WoRMS Chaetognatha (9 updates)</p>
<p>&#8226; WoRMS Cumacea (9 updates)</p>
<p>&#8226; WoRMS Echinoidea (9 updates)</p>
<p>&#8226; WoRMS Gastrotricha (9 updates)</p>
<p>&#8226; WoRMS Gnathostomulida (9 updates)</p>
<p>&#8226; WoRMS Holothuroidea (9 updates)</p>
<p>&#8226; WoRMS Hydrozoa (9 updates)</p>
<p>&#8226; WoRMS Isopoda (9 updates)</p>
<p>&#8226; WoRMS Leptostraca (9 updates)</p>
<p>&#8226; WoRMS Mystacocarida (9 updates)</p>
<p>&#8226; WoRMS Nemertea (9 updates)</p>
<p>&#8226; WoRMS Oligochaeta (9 updates)</p>
<p>&#8226; WoRMS Ophiuroidea (9 updates)</p>
<p>&#8226; WoRMS Phoronida (9 updates)</p>
<p>&#8226; WoRMS Placozoa (9 updates)</p>
<p>&#8226; WoRMS Polychaeta (9 updates)</p>
<p>&#8226; WoRMS Polycystina (9 updates)</p>
<p>&#8226; WoRMS Porifera (9 updates)</p>
<p>&#8226; WoRMS Priapulida (9 updates)</p>
<p>&#8226; WoRMS Proseriata and Kalyptorhynchia (9 updates)</p>
<p>&#8226; WoRMS Remipedia (9 updates)</p>
<p>&#8226; WoRMS Scaphopoda (9 updates)</p>
<p>&#8226; WoRMS Tanaidacea (9 updates)</p>
<p>&#8226; WoRMS Tantulocarida (9 updates)</p>
<p>&#8226; WoRMS Thermosbaenacea (9 updates)</p>
<p>&#8226; WoRMS Xenoturbellida (9 updates)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other changes:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Plantae classification have been updated following ITIS of September 2012.</p>
<p>&#8226; Assembly of CoL proto-GSDs in the phyla Mollusca, Platyhelminthes, Myxosoa, in the class Clitellata (Annelida) and in some flowering plant families has been initiated.</p>
<p>&#8226; A new improved version of Lepidoptera checklist from LepIndex caused reduction of species records for 100K.</p>
<p>&#8226; AlgaeBase data (31K species) have been removed from the Catalogue of Life at the request of the copyright owner. AlgaeBase data may now be licensed directly from Michael Guiry (michael.guiry@algaebase.org).</p>
<p>&#8226; WoRMS Brachyura database has replaced FWCrabs regional checklist</p>
<p>&#8226; Four new languages have been added in the interface: Russian, Lithuanian, Polish and German.</p>
</div>
<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 11th March 2013</p>

<p class="field_header">There are 8 new taxonomic databases:</p>
<div style='margin-left: 10px;'>
<p>&#8226; CoreoideaSF</p>
<p>&#8226; PsocodeaSF</p>
<p>&#8226; FADA Bivalvia</p>
<p>&#8226; FADA Turbellaria</p>
<p>&#8226; MolluscaFW</p>
<p>&#8226; WoRMS Myxozoa</p>
<p>&#8226; WoRMS Mollusca</p>
<p>&#8226; WoRMS Monogenea</p>

</div>
<p>&nbsp;</p>

<p class="field_header">New WoRMS checklists have replaced URMO sectors:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Three new checklists of phylum Chaetognatha, classes Cestoda and Trematoda from WoRMS have replaced corresponding URMO datasets. WoRMS Chaetognatha has been processed via CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">40 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; AphidSF</p>
<p>&#8226; BlattodeaSF</p>
<p>&#8226; EmbiopteraSF (second update)</p>
<p>&#8226; MantodeaSF</p>
<p>&#8226; OrthopteraSF (second update)</p>
<p>&#8226; PhasmidaSF</p>
<p>&#8226; PlecopteraSF (second update)</p>
<p>&#8226; FishBase (second update)</p>
<p>&#8226; FADA Ephemeroptera (second update)</p>
<p>&#8226; 31 WoRMS checklists have been updated through automated process using CoL Workbench templates (ninth update)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other changes:</p>
<div style='margin-left: 10px;'>
<p>&#8226; AlgaeBase data have been removed from the Catalogue of Life at the request of the copyright owner. AlgaeBase data may now be licensed directly from Michael Guiry (michael.guiry@algaebase.org).</p>
<p>&#8226; Updates in Plantae classification (phyla and classes) have been completed. Class Liliopsida is kept in the CoL alongside with class Magnoliopsida for data management convenience.</p>
<p>&#8226; Polish language has been added in the interface (translation completed by Magda Sitko).</p>
</div>
<p>&nbsp;</p>


<br/>
<hr/>
<p>&nbsp;</p>






<p class="iyb-slogan">In the Catalogue of Life, 13th February 2013</p>

<p class="field_header">There is a new contribution from a regional dataset in CoL gap areas:</p>
<div style='margin-left: 10px;'>
<p>&#8226; The Catalogue of Life China contributed a second batch of species from phylum Labyrinthista (Chromista) and class Acantharia (Protozoa), plus flowering plants to fill temporarily gaps in global Catalogue of Life at lower levels of the taxonomic classification (e.g. species, genera). Editorial fine-tuning has been completed by Thomas Kunze, CoL editorial assistant.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">New WoRMS checklists have replace URMO sectors:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Four new checklists of phyla Gastrotricha, Gnathostomulida, Placozoa and Priapulida from WoRMS have replaced corresponding URMO datasets; data have been processed via CoL Workbench templates.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">30 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; EmbiopteraSF: Embioptera Species File</p>
<p>&#8226; OrthopteraSF: Orthoptera Species File</p>
<p>&#8226; 27 WoRMS checklists have been updated through automated process using CoL Workbench templates (eighth update)</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 28th January 2013</p>
<p class="field_header">There is a new contribution from a regional dataset in CoL gap areas:</p>
<div style='margin-left: 10px;'>
<p>&#8226; The Catalogue of Life China contributed a first batch of species from animalian classes Crinoidea, Bivalvia, Gastropoda, Adenophorea, Polychaeta, Malacostraca, Maxillopoda and Insecta (order Coleoptera); and from plant phyla Bryophyta & Pteridophyta to fill temporarily gaps in global Catalogue of Life at lower levels of the taxonomic classification (e.g. species, genera).</p>
</div>
<p>&nbsp;</p>

<p class="field_header">28 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; LIAS: A Global Information System for Lichenized and Non-Lichenized Ascomycetes (2nd update in a year).</p>
<p>&#8226; 27 WoRMS checklists have been updated through automated process using CoL Workbench templates (seventh update)</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 21st December 2012</p>
<p class="field_header">There are two new taxonomic checklists contributed by FADA:</p>
<div style='margin-left: 10px;'>
<p>&#8226; FADA Nematomorpha: World checklist of freshwater Nematomorpha species</p>
<p>&#8226; FADA Ephemeroptera: World checklist of freshwater Ephemeroptera species</p>
</div>
<p>&nbsp;</p>

<p class="field_header">31 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; FADA Rotifera. A new version of Rotifera Database by Hendrik Segers has been taken from FADA project</p>
<p>&#8226; FishBase</p>
<p>&#8226; PlecopteraSF</p>
<p>&#8226; Strepsiptera Database</p>
<p>&#8226; 27 WoRMS checklists have been updated through automated process using CoL Workbench templates (sixth update)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Inactive URLs have been removed from Systema Dipterorum and ILDIS datasets</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 20th November 2012</p>

<p class="field_header">Following ITIS sectors have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Plantae - Pteridophyta (ITIS Regional)</p>
<p>&#8226; Plantae - Magnoliophyta - Magnoliopsida - Ericales - Sarraceniaceae - genus Sarracenia (ITIS Regional)</p> 
<p>&#8226; Animalia - Arthropoda - Insecta - Mantophasmatodea (ITIS Global)</p>
<p>&#8226; Animalia - Chordata - Aves (ITIS Global)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">27 checklists have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 27 WoRMS checklists have been updated through automated process using CoL Workbench templates (fifth update)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other improvements:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 21 pairs of species duplicates have been resolved through whole database.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 25th October 2012*</p>
<center>(* a year without Frank Bisby)</center>

<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'>
<p>&#8226; HymIS Rhopalosomatidae: Hymenoptera Information System, Rhopalosomatidae of the world</p>
</div>
<p>&nbsp;</p>

<p class="field_header">There are new global checklists of flowering plants from ITIS:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Plantae - Magnoliophyta - Liliopsida - Pycnanthaceae (New!)</p>
<p>&#8226; Plantae - Magnoliophyta - Magnoliopsida - Barbeyaceae (New!), Cephalotaceae (New!), Eucommiaceae (New!), Gerrardinaceae (New!), Gesneriaceae, Koeberliniaceae (New!), Lophopyxidaceae (New!), Montiniaceae (New!), Penthoraceae (New!), Petenaeaceae (New!), Rhoipteleaceae (New!).</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Updated sectors:</p>
<div style='margin-left: 10px;'>
<p>&#8226; 27 WoRMS checklists have been updated through automated process using CoL Workbench templates (fourth update)</p>
<p>&#8226; All North American checklists of flowering plants from ITIS have been updated</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other changes:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Classification of flowering plants has been changed on order level following a new classification from ITIS.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 24th September 2012</p>

<p class="field_header">31 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; GloBIS (GART): Global Butterfly Information System</p>
<p>&#8226; ILDIS World Database of Legumes (second update: distribution data have been converted into TDWG Level 4 areas)</p>
<p>&#8226; Scarabs: World Scarabaeidae Database (second update)</p>
<p>&#8226; SysMyr: Systematic Myriapod Database (third update)</p>
<p>&#8226; 27 WoRMS checklists have been updated through automated process using CoL Workbench templates (third update)</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Other corrections:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ICTV/MSL: latest taxonomic scrutiny records and presentation of virus genera have been improved</p>
<p>&#8226; PhytoseiidBase from MitesGSDs: link to a new website and links to online species pages have been added</p>
<p>&#8226; Data provider for family Megascolecidae (Oligochaeta) has been changed back to regional NZIB checklist with  on request of Encyclopedia of Life and Thomas Orrell.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 17th August 2012</p>

<p class="field_header">31 databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; ICTV/MSL: International Committee on Taxonomy of Viruses / Master Species List</p>
<p>&#8226; ILDIS World Database of Legumes (including 4D4Life life zone information with all species)</p>
<p>&#8226; RJB Geranium Taxonomic Information System</p>
<p>&#8226; SysMyr: Systematic Myriapod Database (second update)</p>
<p>&#8226; 27 WoRMS checklists have been updated through automated process using CoL Workbench templates (second update)</p>

</div>
<p>&nbsp;</p>
<p class="field_header">Other issues:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Lithuanian language has been added in the interface.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 26th July 2012</p>

<p class="field_header">27 WoRMS checklists have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; All checklists have been updated through automated process using CoL Workbench templates</p>

</div>
<p>&nbsp;</p>
<p class="field_header">Other issues:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Known bugs in the interface software have been fixed now.</p>
<p>&#8226; Russian language has been added in the interface.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>


<p class="iyb-slogan">In the Catalogue of Life, 25th June 2012</p>

<p class="field_header">Two taxonomic databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; BdelloideaBase: Bdellid & Cunaxid Databases</p>
<p>&#8226; SpidCat: The World Spider Catalog. In request of GSD custodian, SpidCat dataset has been taken via ITIS. Database now appears in the Catalogue of Life under a name "SpidCat via ITIS"</p>

</div>
<p>&nbsp;</p>

<p class="field_header">Apology:</p>
<div style='margin-left: 10px;'>
<p>Present version of the interface contains two bugs: statistics and credits are not displayed correctly in the tree. Multilingual option has been switched off due to difficulties with its editorial management. Please accept our apology for any possible inconvenience. We hope, bugs and interface management difficulties will be sorted soon.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 30th May 2012 (superseded CoL, 23rd May 2012)</p>

<p class="field_header">Three taxonomic databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; LIAS: A Global Information System for Lichenized and Non-Lichenized Ascomycetes</p>
<p>&#8226; MELnet: Melastomataceae.Net</p>
<p>&#8226; Scarabs: World Scarabaeidae Database</p>
</div>
<p>&nbsp;</p>

<p class="field_header">New interface:</p>

<p>CoLs of 30th and 23rd May 2012 have been processed with new conversion tool and released in new user interface ver. 1.8. New functionalities include:</p> 
<div style='margin-left: 10px;'>
<p>&#8226; The operational menu of the Catalogue now can be shown in different languages.</p>
<p>&#8226; Dataset Qualifiers have been introduced on Database Details and Species Details page.</p>
<p>&#8226; Number of species for each taxon in the Catalogue can be found in the Taxonomic Tree.</p>
<p>&#8226; Names of supplier databases are visible with each taxon in the Taxonomic Tree.</p>
<p>&#8226; Users now can leave a feedback for data providers and editors with each taxon in the tree.</p>
<p>&#8226; Thumbnail images are shown with kingdoms and phyla in the Tree.</p>
<p>&#8226; Map of a species distribution is shown on the species page where distribution data are in an appropriate state.</p>
</div>
<p>&nbsp;</p>

<p class="field_header">Apology:</p>
<div style='margin-left: 10px;'>
<p>The present version of the interface contains two bugs: statistics and credits are not displayed correctly in the tree. Interface software does not provide coordination between titles in different languages. Thus, titles in other languages than English are corrupted. Please accept our apology for any possible inconvenience. Bugs will be fixed in nearest future.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 30th April 2012</p>

<p class="field_header">There is a new global checklist from ITIS:</p>
Animalia - Arthropoda - Insecta - Coleoptera - Chrysomeloidea - Chrysomelidae - (subfamily) <span style="color: blue;">Cassidinae</span> <span style="color: red;">(New!)</span>
<p>&nbsp;</p>
<p class="field_header">Two taxonomic databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; GCC: Global Compositae Checklist</p>
<p>&#8226; SysMyr: Systematic Myriapod Database</p>
</div>
<p>&nbsp;</p>
<p class="field_header">Apology:</p>
<div style='margin-left: 10px;'>
<p>The Catalogue of Life Around the Year still operates with user interface 1.6. Please accept our apology for any possible inconvenience.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 15th March 2012</p>
The Catalogue of Life assembly procedures have been switched to the CoL Workbench environment from the beginning of February 2012.
<p>&nbsp;</p>
<p class="field_header">One taxonomic database has been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; LepIndex provides a new version of synonymised taxonomic checklist for Lepidoptera. Due to synonymisation, total number of provisionally accepted species has been reduced from 242,993 to 143,130. This also caused reduction in Catalogue of Life species number for 1.3M.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 3rd February 2012 (= 2012 Annual Checklist)</p>


<p class="field_header">There are five new taxonomic databases:</p>

<div style='margin-left: 10px;'>
<p>&#8226; ChenoBase: World Species List of Chenopodiaceae</p>
<p>&#8226; CilCat: The World Ciliate Catalog</p>
<p>&#8226; EbenaBase: World Species List of Ebenaceae</p>
<p>&#8226; Umbellifers: World Umbellifer Database</p>
<p>&#8226; WoRMS Hydrozoa: World Hydrozoa Database</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Eleven taxonomic databases have been updated:</p>

<div style='margin-left: 10px;'> 
<p>&#8226; AnnonBase: World Species List of Annonaceae</p> 
<p>&#8226; ELPT: Early Land Plants Today (liverworts and hornworts)</p>
<p>&#8226; FishBase (2nd update in a year)</p>
<p>&#8226; FWCrabs: Neotropical Freshwater Crabs Catalogue</p>
<p>&#8226; GCC: Global Compositae Checklist</p>
<p>&#8226; Odonata: Global Species Database Odonata</p>
<p>&#8226; Scarabs: World Scarabaeidae Database (2nd update in a year)</p>
<p>&#8226; Tineidae NHM: Global Taxonomic Database of Tineidae (Lepidoptera)</p>
<p>&#8226; TITAN: Cerambycidae database</p>
<p>&#8226; WCSP: World Checklist of Selected Plant Families</p>
<p>&#8226; ZOBODAT Vespoidea: Zoological-Botanical Database (Vespoidea)</p>
</div>
<br/>
<p class="field_header">Other changes:</p>

<div style='margin-left: 10px;'> 
<p>&#8226; ITIS database has been split for ITIS Global (with global checklists) and ITIS Regional (with New World checklists of various dates, completeness and geographical coverage)</p>
<p>&#8226; Two WoRMS databases, Brachiopoda World Database and Phoronida World Database, are credited separately now</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 5th December 2011</p>
<p class="field_header">There are seven new global checklists from WoRMS:</p>

<div style='margin-left: 10px;'> 
<p>&#8226; WoRMS Brachyura: World List of Marine Brachyura</p>
<p>&#8226; WoRMS Echinoidea: World Echinoidea Database</p>
<p>&#8226; WoRMS Holothuroidea: World List of Holothuroidea</p>
<p>&#8226; WoRMS Leptostraca: World Leptostraca Database</p>
<p>&#8226; WoRMS Polycystina: World List of Polycystina</p>
<p>&#8226; WoRMS Scaphopoda: World List of Scaphopoda</p>
<p>&#8226; WoRMS Tanaidacea: World List of Tanaidacea</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Nineteen WoRMS checklists have been updated:</p>

<div style='margin-left: 10px;'>
<p>&#8226; WoRMS Asteroidea: World Asteroidea Database</p> 
<p>&#8226; WoRMS Bochusacea: World List of Bochusacea</p> 
<p>&#8226; WoRMS Brachiopoda: World Brachiopoda Database</p> 
<p>&#8226; WoRMS Brachypoda: World List of Brachypoda</p> 
<p>&#8226; WoRMS Bryozoa: World Marine Bryozoa Database</p> 
<p>&#8226; WoRMS Cumacea: World Cumacea Database</p> 
<p>&#8226; WoRMS Isopoda: World List of Marine, Freshwater and Terrestrial Isopod Crustaceans</p> 
<p>&#8226; WoRMS Mystacocarida: World List of Mystacocarida</p> 
<p>&#8226; WoRMS Nemertea: World List of Nemertea</p> 
<p>&#8226; WoRMS Oligochaeta: World List of Marine Oligochaeta</p> 
<p>&#8226; WoRMS Ophiuroidea: World Ophiuroidea Database</p> 
<p>&#8226; WoRMS Phoronida: World Phoronida Database</p> 
<p>&#8226; WoRMS Polychaeta: World Polychaeta Database</p>
<p>&#8226; WoRMS Porifera: World Porifera Database</p> 
<p>&#8226; WoRMS Proseriata and Kalyptorhynchia: World database of Proseriata & Kalyptorhynchia</p> 
<p>&#8226; WoRMS Remipedia: World Remipedia Database</p> 
<p>&#8226; WoRMS Tantulocarida: World List of Tantulocarida</p> 
<p>&#8226; WoRMS Thermosbaenacea: World List of Thermosbaenacea</p>
<p>&#8226; WoRMS Xenoturbellida</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 24th October 2011</p>
<p class="field_header">There is a new taxonomic database:</p>
<div style='margin-left: 10px;'> 
<p>&#8226; Global Strepsiptera Database by J. Kathirithamby.</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Eleven taxonomic databases have been updated:</p>

<div style='margin-left: 10px;'>
<p>&#8226; 3i Cicadellinae,</p> 
<p>&#8226; 3i Typhlocybinae,</p>
<p>&#8226; BdelloideaBase (former CunaxidBase; new family Bdellidae has been added),</p>
<p>&#8226; BlattodeaSF (trial upload),</p>
<p>&#8226; CIPA,</p>
<p>&#8226; Conifer Database (new release),</p>
<p>&#8226; COOL,</p>
<p>&#8226; FLOW,</p>
<p>&#8226; Nomen.eumycetozoa.com,</p>
<p>&#8226; Psyl'list,</p>
<p>&#8226; World Gracillariidae.</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Apology:</p>

<div style='margin-left: 10px;'>
<p>The CoL assembly process continues to be in transition from &quot;old&quot; to &quot;new&quot; base schema and data processing software. Due to these major changes, some data may appear in a raw form or even not be displayed in present interface version. We apologize for any possible inconvenience.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 26th July 2011</p>
<p class="field_header">There is a new taxonomic database:</p>

<div style='margin-left: 10px;'> 
<p>&#8226; MELnet: Melastomataceae.Net database by S.S. Renner & al.</p>
<i>Thus, CoL of July 2011 celebrates an arrival of 100th database.</i>
</div>

<p>&nbsp;</p>
<p class="field_header">New global checklists from ITIS:</p>

<div style='margin-left: 10px;'>
<p>&#8226; Animalia - Arthropoda - Maxillopoda - Calanoida - family Aetideidae</p>
<p>&#8226; Animalia - Arthropoda - Insecta - order Mecoptera</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - families  Bostrichidae, Dytiscidae, Histeridae &amp; Hydraenidae</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Six taxonomic databases have been updated:</p>

<div style='margin-left: 10px;'>
<p>&#8226; FishBase,</p>
<p>&#8226; LIAS,</p>
<p>&#8226; Scarabs,</p>
<p>&#8226; Conifer Database (additional references),</p>
<p>&#8226; SpmWeb,</p>
<p>&#8226; ITIS (superfamily Buprestoidea and family Tetratomidae from Coleoptera)</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Other improvements:</p>

<div style='margin-left: 10px;'>
<p>&#8226; Accepted names and synonyms passed additional cleanings in the database</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 3rd January 2011</p>
<p class="field_header">There are 15 new taxonomic databases:</p>
<div style='margin-left: 10px;'> 
<p>&#8226; 3i Cicadellinae by D. Takiya & D. Dmitriev</p>
<p>&#8226; 3i Typhlocybinae by D. Dmitriev</p>
<p>&#8226; Embioptera Species File Online (ESF) by M. Maehr</p>
<p>&#8226; Membracoidea of the World Database (MOWD) by S. McKamey</p>
<p>&#8226; Spider Mites Web (SpmWeb) by A. Migeon & F. Dorkeld</p>
<p>&#8226; WoRMS Asteroidea by C.L. Mah</p>
<p>&#8226; WoRMS Bochusacea by G.A. Boxshall</p>
<p>&#8226; WoRMS Brachypoda by G.A. Boxshall</p>
<p>&#8226; WoRMS Isopoda by M. Schotte, C.B. Boyko, N.L. Bruce, G.C.B. Poore, S. Taiti, G.D.F. Wilson (eds)</p>
<p>&#8226; WoRMS Mystacocarida by G.A. Boxshall</p>
<p>&#8226; WoRMS Nemertea by J.L. Norenburg</p>
<p>&#8226; WoRMS Polychaeta by G. Read & K. Fauchald</p>
<p>&#8226; WoRMS Remipedia by S. Koenemann, M. Hoenemann & T. Stemme (eds)</p>
<p>&#8226; WoRMS Tantulocarida (families Basipodellidae, Deoterthridae, Doryphallophoridae, Microdajidae) by G.A. Boxshall</p>
<p>&#8226; WoRMS Thermosbaenacea by G. Poore</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Updates in ITIS sectors:</p>

<div style='margin-left: 10px;'>

<p>&#8226; ITIS phylum Sipuncula has replaced data previously provided by URMO.</p> 
Following ITIS sectors have also been updated: 
<p>&#8226; Animalia - Arthropoda - Maxillopoda - Calanoida - family Aetideidae (World checklist)</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - family Sphaeriusidae</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - Cucujoidea - family Corylophidae (N. American checklist)</p>
<p>&#8226; Animalia - Arthropoda - Insecta - Coleoptera - Tenebrionoidea - families Mycetophagidae & Tetratomidae (N. American checklists)</p>
<p>&#8226; Animalia - Chordata - Mammalia - Carnivora - Canidae - species Vulpes vulpes</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Other improvements:</p>

<div style='margin-left: 10px;'>
<p>ILDIS common names records have been atomized by names, languages and countries of usage.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 2nd October 2010</p>
<p class="field_header">There are three new taxonomic databases:</p>
<div style='margin-left: 10px;'> 
<p>&#8226; CunaxidBase: Family Cunaxidae Database by J. den Heyer.</p>
<p>&#8226; LIAS: A Global Information System for Lichenized and Non-Lichenized Ascomycetes by G. Rambold as the lead editor (LIAS database has replaced lichen taxa previously provided by Species Fungorum).</p>
<p>&#8226; WoRMS Bryozoa: World Marine Bryozoa Database by P. Bock & D. Gordon (WoRMS Bryozoa has replaced bryozoan taxa previously provided by ITIS).</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Four taxonomic databases have been updated:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Lacistemataceae Holistic Database</p>
<p>&#8226; SalticidDB</p>
<p>&#8226; World Scarabaeidae Database</p>
<p>&#8226; WTaxa</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Additional data has been contributed:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Aljos Farjon (Conifer Database) contributed over 4,000 new Conifer common names in 20 languages as a result of his 4D4Life pilot project.</p>
<p>&#8226; Paul Schoolmeesters (Scarabs database) contributed 11,720 new species from the family Melolonthidae as a result of his 4D4Life pilot project.</p>
</div>

<p>&nbsp;</p>
<p class="field_header">New feature:</p>

<div style='margin-left: 10px;'>
<p>A full list of citations for the contributing databases, using the recommended style, is now available from the how to cite page at <a href = 'http://www.catalogueoflife.org/col/info/cite'>www.catalogueoflife.org/col/info/cite</a>. These may be used for copying & pasting such citations.</p>
</div>

<p>&nbsp;</p>
<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the Catalogue of Life, 1st July 2010</p>
<p class="field_header">Eight taxonomic databases have been updated:</p>
<div style='margin-left: 10px;'> 
<p>&#8226; Aphid Species File,</p>
<p>&#8226; Blattodea Species File,</p>
<p>&#8226; Conifer Database,</p>
<p>&#8226; Global Taxonomic Database of Gracillariidae,</p>
<p>&#8226; Orthoptera Species File,</p>
<p>&#8226; Phasmida Species File,</p>
<p>&#8226; Plecoptera Species File,</p>
<p>&#8226; Mantodea Species File</p>
</div>

<p>&nbsp;</p>
<p class="field_header">The following bugs have been fixed:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Missing order names in some ITIS sectors returned back.</p>
<p>&#8226; 175 ITIS family names have been misplaced in superfamily field in AC10. Corrected in this version.</p>
<p>&#8226; 52,654 empty infraspecific marker values caused the problem with species and infraspecific taxa statistics in AC10. Problem fixed in this version.</p>
<p>&#8226; 33,017 missing common names have been returned back to the database.</p>
<p>&#8226; Position of the family Poaceae in the classification have been corrected.</p>
<p>&#8226; Redundant phylum name Hepatophyta has been deleted. All liverworts species are placed in the phylum Marchantiophyta.</p>
<p>&#8226; Few duplications in species authorstrings have been fixed.</p>
</div>

<p>&nbsp;</p>
<p class="field_header">Changes in the management classification:</p>
<div style='margin-left: 10px;'>
<p>&#8226; Phylum name "Ectoprocta" has been changed to "Bryozoa" in response to request from Dennis Gordon (22 July 2010)</p>

<p>&nbsp;</p>
</div>
<?php
echo $this->navigator_bottom;
?>
