<?php
/**
 * Annual Checklist Interface
 *
 * about.phtml
 * Info - Special 2010 Edition
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
printf($this->translate('Info_special_edition'), $this->app->edition);
?>
</div>
<?php echo $this->navigator_top;?>
<div class="info_content">




<p class="iyb-slogan">In this release of the Catalogue of Life<br><span style="font-weight:normal">(2020-01-10 Beta)</span></p>
<div style='margin-left: 10px;'>
<p>
Between May and December 2019, the Catalogue of Life migrated in a new software environment developed by CoL+ GBIF project with the participation of Olaf Banki as a PI, Markus Döring and Ayco Holleman as back-end developers, and Thomas Jeppesen as a front-end developer.
</p>
<p>
We are presenting a first pilot release of the CoL database which was generated in a new environment. It includes data from 166 GSDs almost identical to the 2019 Annual Checklist. Four regional and thematic checklists, which temporarily filled taxonomic gaps in the CoL, have been removed from the global checklist: ITIS Regional, Catalogue of Life China, New Zealand Inventory of Biodiversity and some taxa from The Paleobiology Database. These checklists will appear in a regional component of the CoL.
</p>
<p>
Only World Scarabaeidae Database has been updated for a new version in this pilot release.
</p>
</div>
<p>&nbsp;</p>

<br/>
<hr/>
<p>&nbsp;</p>

<p class="iyb-slogan">In the 2019 Annual Checklist<br><span style="font-weight:normal">(21st April 2019)</span></p>
<div style='margin-left: 10px;'>
<p>
2019 Annual Checklist contained contributions from 172 taxonomic databases with information on 1,837,565 living and 63,418 extinct species, 160,909 living and 590 extinct infraspecific taxa which belong to 184,526 genera, 12,267 families, 1,643 orders, 387 classes, 104 phyla and 7 kingdoms plus viruses, it also included 1,710,092 synonyms and 437,994 common names. More information is available at <a href= "http://www.catalogueoflife.org/annual-checklist/2019/info/ac" target="_blank">www.catalogueoflife.org/annual-checklist/2019</a>.
</p>
</div>
<p>&nbsp;</p>
 
</div>

<?php
echo $this->navigator_bottom;
?>
