<?php
/**
 * Annual Checklist Interface
 *
 * websites.phtml
 * Info - Websites page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Web_sites')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">

<p class="field_header">Annual Checklist editions of previous years:</p>
<div style="margin-left:2em">
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2019/info/ac" target="_blank">2019 Annual Checklist</a>, 1,900,983 species (incl. 63,418 extinct species)
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2018/info/ac" target="_blank">2018 Annual Checklist</a>, 1,803,488 species (incl. 59,284 extinct species)
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2017/info/ac" target="_blank">2017 Annual Checklist</a>, 1,713,852 species (incl. 49,346 extinct species)
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2016/info/ac" target="_blank">2016 Annual Checklist</a>, 1,640,969 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2015/info/ac" target="_blank">2015 Annual Checklist</a>, 1,606,554 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2014/info/ac" target="_blank">2014 Annual Checklist</a>, 1,578,063 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2013/info/ac" target="_blank">2013 Annual Checklist</a>, 1,352,112 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2012/info/ac" target="_blank">2012 Annual Checklist</a>, 1,404,038 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2011/info/ac" target="_blank">2011 Annual Checklist</a>, 1,347,224 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2010/info/ac" target="_blank">2010 Annual Checklist</a>, 1,257,735 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2009/info_2009_checklist.php" target="_blank">2009 Annual Checklist</a>, 1,160,711 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2008/info_2008_checklist.php" target="_blank">2008 Annual Checklist</a>, 1,105,589 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2007/info_2007_checklist.php" target="_blank">2007 Annual Checklist</a>, 1,008,965 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2006/info_2006_checklist.php" target="_blank">2006 Annual Checklist</a>, 884,552 species
<p><a href= "http://www.catalogueoflife.org/annual-checklist/2005/info_source_dbs.php" target="_blank">2005 Annual Checklist</a>, 526,323 species
</div> 
<p class="field_header">Latest version of the CoL monthly editions:</p>
<p><a href= "http://www.catalogueoflife.org/col" target="_blank">www.catalogueoflife.org/col</a></p>

<p class="field_header">Darwin Core Archives of monthly editions:</p>
<p><a href= "http://www.catalogueoflife.org/DCA_Export/archive.php" target="_blank">http://www.catalogueoflife.org/DCA_Export/archive.php</a></p>

<p class="field_header">Web service:</p>
<p>Species 2000 provides web services to facilitate automated access to
the Annual Checklist by computer programs. Please visit
<a href= "http://www.catalogueoflife.org/content/web-services">http://www.catalogueoflife.org/content/web-services</a> for
more information.</p>

<p class="field_header">CoL Download Service in Darwin Core Archive:</p>
<p><a href= "http://www.catalogueoflife.org/DCA_Export" target="_blank">http://www.catalogueoflife.org/DCA_Export</a></p>

<p class="field_header">CoL website:</p>
<p><a href= "http://www.catalogueoflife.org" target="_blank">www.catalogueoflife.org</a></p>

<p class="field_header">CoL Twitter:</p>
<p><a href= "https://twitter.com/catalogueoflife" target="_blank">https://twitter.com/catalogueoflife</a></p>

<p class="field_header">A list of publications that use, mention or refer to the Catalogue of Life compiled by Integrated Marine Information System (IMIS):</p>
<p><a href= "http://www.vliz.be/en/catalogue?module=ref&show=955" target="_blank">http://www.vliz.be/en/catalogue?module=ref&show=955</a></p>

</div>
<?php
echo $this->navigator_bottom;
?>
